import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import readline from 'node:readline';
import { Command } from 'commander';
import {
  deleteConfigKey,
  readConfig,
  redactConfig,
  resolveConfigPath,
  resolveAgentPayHome,
  type WlfiConfig,
} from '../../packages/config/src/index.js';
import {
  cleanupAutoGeneratedBootstrapArtifacts,
  type CleanupBootstrapArtifactsResult,
} from './bootstrap-artifacts.js';
import {
  DAEMON_PASSWORD_KEYCHAIN_SERVICE,
} from './keychain.js';
import {
  deleteStoredAgentAuthToken,
  resolveAgentAuthStorageService,
} from './agent-auth-storage.js';
import {
  LAUNCHD_UNINSTALL_SCRIPT_NAME,
  resolveLaunchDaemonHelperScriptPath,
} from './launchd-assets.js';
import {
  resolveManagedDaemonPlatformSpec,
} from './managed-daemon-platform.js';
import { assertManagedDaemonPlatform } from './platform-support.js';
import { promptHiddenTty } from './hidden-tty-prompt.js';
import { createSudoSession } from './sudo.js';
import { resolveSystemdHelperScriptPath, SYSTEMD_UNINSTALL_SCRIPT_NAME } from './systemd-assets.js';

const MANAGED_DAEMON_SPEC = resolveManagedDaemonPlatformSpec(
  process.platform === 'linux' ? 'linux' : 'darwin',
);
const DEFAULT_LAUNCH_DAEMON_LABEL = MANAGED_DAEMON_SPEC.label;
const DEFAULT_MANAGED_DAEMON_SOCKET = MANAGED_DAEMON_SPEC.daemonSocket;
const DEFAULT_MANAGED_STATE_FILE = MANAGED_DAEMON_SPEC.stateFile;
const DEFAULT_LAUNCH_DAEMON_PLIST = MANAGED_DAEMON_SPEC.serviceFile;
const DEFAULT_MANAGED_ROOT_DIR = MANAGED_DAEMON_SPEC.rootDir;
const DEFAULT_MANAGED_STATE_DIR = MANAGED_DAEMON_SPEC.stateDir;
const DEFAULT_MANAGED_LOG_DIR = MANAGED_DAEMON_SPEC.logDir ?? '';
const DEFAULT_MANAGED_RELAY_DAEMON_TOKEN_FILE = MANAGED_DAEMON_SPEC.relayDaemonTokenFile;
const GLOBAL_NPM_CLI_PACKAGE_NAME = '@worldlibertyfinancial/agentpay-sdk';
const LEGACY_GLOBAL_NPM_CLI_LABEL = 'legacy global npm AgentPay SDK CLI';
const ONE_CLICK_INSTALL_MANIFEST_FILENAME = 'one-click-install-manifest.json';
const ONE_CLICK_RC_BLOCK_START = '# >>> agentpay-sdk >>>';
const ONE_CLICK_RC_BLOCK_END = '# <<< agentpay-sdk <<<';
const ONE_CLICK_PATH_SHIM_MARKER = '# agentpay-sdk one-click PATH shim';
const MAX_SECRET_STDIN_BYTES = 16 * 1024;
const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];

interface ProgressHandle {
  succeed(message?: string): void;
  fail(message?: string): void;
}

interface AdminResetOptions {
  yes?: boolean;
  nonInteractive?: boolean;
  deleteConfig?: boolean;
  json?: boolean;
}

interface AdminUninstallOptions {
  yes?: boolean;
  nonInteractive?: boolean;
  json?: boolean;
}

export interface CleanupLocalAdminResetStateResult {
  agentKeyId: string | null;
  keychain: {
    removed: boolean;
    service: string | null;
    error: string | null;
  };
  config: {
    path: string;
    existed: boolean;
    deleted: boolean;
    clearedAgentKeyId: boolean;
    clearedLegacyAgentAuthToken: boolean;
    clearedWalletMetadata: boolean;
    value: Record<string, unknown> | null;
  };
  bootstrapArtifacts: {
    attempted: boolean;
    action: 'deleted';
    fileCount: number;
    cleanedCount: number;
    skippedCount: number;
    error: string | null;
  };
}

interface CleanupLocalAdminResetStateDeps {
  platform?: NodeJS.Platform;
  existsSync?: (targetPath: string) => boolean;
  resolveConfigPath?: () => string;
  resolveAgentPayHome?: () => string;
  readConfig?: () => WlfiConfig;
  deleteConfigKey?: (key: keyof WlfiConfig) => WlfiConfig;
  deleteAgentAuthToken?: (agentKeyId: string) => boolean;
  unlinkSync?: (targetPath: string) => void;
  cleanupBootstrapArtifacts?: (action: 'deleted') => CleanupBootstrapArtifactsResult;
}

export interface CleanupLocalAdminUninstallStateResult {
  agentKeyId: string | null;
  keychain: {
    removed: boolean;
    service: string | null;
    error: string | null;
  };
  config: {
    path: string;
    existed: boolean;
    deleted: boolean;
  };
  agentpayHome: {
    path: string;
    existed: boolean;
    deleted: boolean;
  };
  oneClickInstaller: OneClickInstallerCleanupResult;
}

interface GlobalCliUninstallResult {
  packageName: string;
  packageManager: 'npm';
  attempted: boolean;
  removed: boolean;
  installPath: string | null;
  skippedReason: string | null;
}

interface OneClickInstallManifest {
  version?: number;
  installRoot?: string;
  agentpayHome?: string;
  shellRcPath?: string;
  skillTargets?: string[];
  cursorArtifactPaths?: string[];
  pathShimPaths?: string[];
}

interface OneClickInstallerCleanupResult {
  manifest: {
    path: string;
    existed: boolean;
    removedWithAgentPayHome: boolean;
    warning: string | null;
  };
  shellRcFilesUpdated: string[];
  skillTargetsRemoved: string[];
  cursorArtifactsRemoved: string[];
  pathShimsRemoved: string[];
  installRoot: {
    path: string | null;
    removed: boolean;
    skippedReason: string | null;
  };
}

interface CleanupLocalAdminUninstallStateDeps {
  platform?: NodeJS.Platform;
  existsSync?: (targetPath: string) => boolean;
  resolveConfigPath?: () => string;
  resolveAgentPayHome?: () => string;
  readConfig?: () => WlfiConfig;
  deleteAgentAuthToken?: (agentKeyId: string) => boolean;
  rmSync?: (targetPath: string, options: { recursive: boolean; force: boolean }) => void;
  readFileSync?: (targetPath: string, encoding: BufferEncoding) => string;
  writeFileSync?: (targetPath: string, data: string, encoding: BufferEncoding) => void;
  readdirSync?: (targetPath: string) => string[];
  homedir?: () => string;
}

function renderError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function validateSecret(value: string, label: string): string {
  if (Buffer.byteLength(value, 'utf8') > MAX_SECRET_STDIN_BYTES) {
    throw new Error(`${label} must not exceed ${MAX_SECRET_STDIN_BYTES} bytes`);
  }
  if (!value.trim()) {
    throw new Error(`${label} must not be empty or whitespace`);
  }
  return value;
}

async function promptHidden(query: string, label: string): Promise<string> {
  const answer = await promptHiddenTty(query, `${label} is required; rerun on a local TTY`);
  return validateSecret(answer, label);
}

async function promptVisible(query: string): Promise<string> {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    throw new Error('admin reset requires --yes in non-interactive environments');
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true,
  });

  const answer = await new Promise<string>((resolve) => {
    rl.question(query, resolve);
  });
  rl.close();
  return answer.trim();
}

const sudoSession = createSudoSession({
  promptPassword: async () =>
    await promptHidden(
      'System admin password for sudo (input hidden; required to uninstall the root-managed daemon and delete its state): ',
      'System admin password for sudo',
    ),
});

function isSudoWrappedInvocation(): boolean {
  return (
    typeof process.geteuid === 'function' &&
    process.geteuid() === 0 &&
    typeof process.env.SUDO_UID === 'string' &&
    process.env.SUDO_UID.trim().length > 0
  );
}

function assertNotInvokedViaSudo(commandName: string): void {
  if (!isSudoWrappedInvocation()) {
    return;
  }
  throw new Error(
    `run \`agentpay ${commandName}\` as your normal local user, not with sudo; the CLI prompts for sudo internally and running it as root can target the wrong local AgentPay home`,
  );
}

function createProgress(message: string, enabled = true): ProgressHandle {
  if (!enabled) {
    return {
      succeed() {},
      fail() {},
    };
  }

  if (!process.stderr.isTTY) {
    process.stderr.write(`==> ${message}\n`);
    return {
      succeed(finalMessage = message) {
        process.stderr.write(`✓ ${finalMessage}\n`);
      },
      fail(finalMessage = `${message} failed`) {
        process.stderr.write(`✗ ${finalMessage}\n`);
      },
    };
  }

  let frameIndex = 0;
  const render = (prefix: string, currentMessage: string) => {
    process.stderr.write(`\r\u001b[2K${prefix} ${currentMessage}`);
  };

  render(SPINNER_FRAMES[frameIndex], message);
  const timer = setInterval(() => {
    frameIndex = (frameIndex + 1) % SPINNER_FRAMES.length;
    render(SPINNER_FRAMES[frameIndex], message);
  }, 80);

  const stop = (prefix: string, finalMessage: string) => {
    clearInterval(timer);
    render(prefix, finalMessage);
    process.stderr.write('\n');
  };

  return {
    succeed(finalMessage = message) {
      stop('✓', finalMessage);
    },
    fail(finalMessage = `${message} failed`) {
      stop('✗', finalMessage);
    },
  };
}

function print(payload: unknown, asJson: boolean | undefined): void {
  if (asJson) {
    console.log(JSON.stringify(payload, null, 2));
    return;
  }
  /* c8 ignore start -- this module only calls print() for JSON output; non-JSON summaries bypass this helper */
  if (typeof payload === 'string') {
    console.log(payload);
    return;
  }
  console.dir(payload, { depth: null, colors: process.stdout.isTTY });
  /* c8 ignore stop */
}

async function managedPathExists(targetPath: string): Promise<boolean> {
  const result = await sudoSession.run(['/bin/test', '-e', targetPath]);
  if (result.code === 0) {
    return true;
  }
  if (
    result.code === 1 &&
    !/password is required|try again|authentication failed|sorry/iu.test(result.stderr)
  ) {
    return false;
  }
  throw new Error(
    result.stderr.trim() ||
      result.stdout.trim() ||
      `failed to inspect managed path '${targetPath}' (exit code ${result.code})`,
  );
}

async function assertManagedUninstallArtifactsRemoved(targetPaths: string[]): Promise<void> {
  const remaining: string[] = [];
  for (const targetPath of targetPaths) {
    if (await managedPathExists(targetPath)) {
      remaining.push(targetPath);
    }
  }
  if (remaining.length > 0) {
    throw new Error(
      `admin uninstall left managed root-owned files behind: ${remaining.join(', ')}`,
    );
  }
}

function assertLocalUninstallArtifactsRemoved(result: CleanupLocalAdminUninstallStateResult): void {
  const remaining: string[] = [];
  if (result.config.existed && fs.existsSync(result.config.path)) {
    remaining.push(result.config.path);
  }
  if (result.agentpayHome.existed && fs.existsSync(result.agentpayHome.path)) {
    remaining.push(result.agentpayHome.path);
  }
  if (remaining.length > 0) {
    throw new Error(`admin uninstall left local AgentPay files behind: ${remaining.join(', ')}`);
  }
}

function printResetSummary(result: {
  daemon: {
    label: string;
    daemonSocket: string;
    relayDaemonTokenFile: string;
    stateFile: string;
  };
  local: CleanupLocalAdminResetStateResult;
}): void {
  const lines = [
    'reset complete',
    `managed daemon removed: ${result.daemon.label}`,
    `managed state deleted: ${result.daemon.stateFile}`,
    `managed socket removed: ${result.daemon.daemonSocket}`,
    `managed relay token removed: ${result.daemon.relayDaemonTokenFile}`,
  ];

  if (result.local.agentKeyId) {
    lines.push(`old agent key cleared: ${result.local.agentKeyId}`);
  } else {
    lines.push('old agent key cleared: no configured agent key was found');
  }

  if (result.local.config.deleted) {
    lines.push(`config deleted: ${result.local.config.path}`);
  } else if (result.local.config.existed) {
    lines.push(`config kept: ${result.local.config.path}`);
    if (result.local.config.clearedWalletMetadata) {
      lines.push('wallet metadata cleared from kept config');
    }
  } else {
    lines.push(`config not found: ${result.local.config.path}`);
  }
  if (result.local.keychain.error) {
    lines.push(`local credential cleanup warning: ${result.local.keychain.error}`);
  }

  if (result.local.bootstrapArtifacts.error) {
    lines.push(`bootstrap artifact cleanup warning: ${result.local.bootstrapArtifacts.error}`);
  } else if (result.local.bootstrapArtifacts.attempted) {
    lines.push(
      `bootstrap artifacts deleted: ${result.local.bootstrapArtifacts.cleanedCount}/${result.local.bootstrapArtifacts.fileCount}`,
    );
  }

  lines.push('next: run `agentpay admin setup` to create a new wallet');
  console.log(lines.join('\n'));
}

function resolveLaunchDaemonUninstallScriptPath(config?: WlfiConfig): string {
  if (process.platform === 'linux') {
    return resolveSystemdHelperScriptPath(SYSTEMD_UNINSTALL_SCRIPT_NAME, config);
  }
  return resolveLaunchDaemonHelperScriptPath(LAUNCHD_UNINSTALL_SCRIPT_NAME, config);
}

function readConfigIfPresent(): WlfiConfig | undefined {
  return fs.existsSync(resolveConfigPath()) ? readConfig() : undefined;
}

function findNearestPackageRoot(startPath: string): string | null {
  let current = path.resolve(startPath);
  let candidate = fs.statSync(current, { throwIfNoEntry: false })?.isDirectory()
    ? current
    : path.dirname(current);

  while (true) {
    if (fs.existsSync(path.join(candidate, 'package.json'))) {
      return candidate;
    }
    const parent = path.dirname(candidate);
    if (parent === candidate) {
      return null;
    }
    candidate = parent;
  }
}

function resolveCurrentGlobalNpmCliInstallPath(): string | null {
  const scriptPath = process.argv[1];
  if (!scriptPath) {
    return null;
  }

  const packageRoot = findNearestPackageRoot(scriptPath);
  if (!packageRoot) {
    return null;
  }

  try {
    const parsed = JSON.parse(fs.readFileSync(path.join(packageRoot, 'package.json'), 'utf8')) as {
      name?: unknown;
    };
    if (parsed.name !== GLOBAL_NPM_CLI_PACKAGE_NAME) {
      return null;
    }
  } catch {
    return null;
  }

  const marker = `${path.sep}node_modules${path.sep}`;
  if (!packageRoot.includes(marker)) {
    return null;
  }

  const npmRootResult = spawnSync('npm', ['root', '-g'], { encoding: 'utf8' });
  if (npmRootResult.error) {
    throw new Error(
      `failed to inspect the ${LEGACY_GLOBAL_NPM_CLI_LABEL}: ${renderError(npmRootResult.error)}`,
    );
  }
  if (npmRootResult.status !== 0) {
    throw new Error(
      npmRootResult.stderr.trim()
        || npmRootResult.stdout.trim()
        || `failed to inspect the ${LEGACY_GLOBAL_NPM_CLI_LABEL} (exit code ${npmRootResult.status})`,
    );
  }

  const npmRoot = npmRootResult.stdout.trim();
  if (!npmRoot) {
    throw new Error(
      `failed to inspect the ${LEGACY_GLOBAL_NPM_CLI_LABEL}: npm root -g returned no path`,
    );
  }

  const expectedInstallPath = path.join(npmRoot, ...GLOBAL_NPM_CLI_PACKAGE_NAME.split('/'));
  return path.resolve(packageRoot) === path.resolve(expectedInstallPath) ? expectedInstallPath : null;
}

function uninstallCurrentGlobalNpmCli(): GlobalCliUninstallResult {
  const installPath = resolveCurrentGlobalNpmCliInstallPath();
  if (!installPath) {
    return {
      packageName: GLOBAL_NPM_CLI_PACKAGE_NAME,
      packageManager: 'npm',
      attempted: false,
      removed: false,
      installPath: null,
      skippedReason: 'current command is not running from a legacy global npm install',
    };
  }

  const uninstallResult = spawnSync(
    'npm',
    ['uninstall', '--global', GLOBAL_NPM_CLI_PACKAGE_NAME],
    { encoding: 'utf8' },
  );
  if (uninstallResult.error) {
    throw new Error(
      `failed to uninstall the ${LEGACY_GLOBAL_NPM_CLI_LABEL}: ${renderError(uninstallResult.error)}`,
    );
  }
  if (uninstallResult.status !== 0) {
    throw new Error(
      uninstallResult.stderr.trim()
        || uninstallResult.stdout.trim()
        || `failed to uninstall the ${LEGACY_GLOBAL_NPM_CLI_LABEL} (exit code ${uninstallResult.status})`,
    );
  }

  return {
    packageName: GLOBAL_NPM_CLI_PACKAGE_NAME,
    packageManager: 'npm',
    attempted: true,
    removed: true,
    installPath,
    skippedReason: null,
  };
}

export function managedDaemonResetArtifactPaths(): string[] {
  return [
    DEFAULT_MANAGED_STATE_FILE,
    DEFAULT_MANAGED_DAEMON_SOCKET,
    DEFAULT_MANAGED_RELAY_DAEMON_TOKEN_FILE,
    ...(MANAGED_DAEMON_SPEC.daemonPasswordFile ? [MANAGED_DAEMON_SPEC.daemonPasswordFile] : []),
  ];
}

export function cleanupLocalAdminResetState(
  options: { deleteConfig?: boolean } = {},
  deps: CleanupLocalAdminResetStateDeps = {},
): CleanupLocalAdminResetStateResult {
  const platform = deps.platform ?? process.platform;
  const existsSync = deps.existsSync ?? fs.existsSync;
  const resolveConfigPathImpl = deps.resolveConfigPath ?? resolveConfigPath;
  const resolveAgentPayHomeImpl = deps.resolveAgentPayHome ?? resolveAgentPayHome;
  const readConfigImpl = deps.readConfig ?? readConfig;
  const deleteConfigKeyImpl = deps.deleteConfigKey ?? deleteConfigKey;
  const deleteAgentAuthTokenImpl =
    deps.deleteAgentAuthToken ??
    ((agentKeyId: string) => deleteStoredAgentAuthToken(agentKeyId, platform));
  const unlinkSyncImpl = deps.unlinkSync ?? fs.unlinkSync;
  const cleanupBootstrapArtifactsImpl =
    deps.cleanupBootstrapArtifacts ?? cleanupAutoGeneratedBootstrapArtifacts;

  const configPath = resolveConfigPathImpl();
  const agentpayHome = resolveAgentPayHomeImpl();
  const configExists = existsSync(configPath);
  const currentConfig = configExists ? readConfigImpl() : null;
  const agentKeyId = currentConfig?.agentKeyId ?? currentConfig?.wallet?.agentKeyId ?? null;
  const clearedAgentKeyId = currentConfig?.agentKeyId !== undefined;
  const clearedLegacyAgentAuthToken = currentConfig?.agentAuthToken !== undefined;
  const clearedWalletMetadata = currentConfig?.wallet !== undefined;
  let keychainRemoved = false;
  let keychainError: string | null = null;
  if (agentKeyId) {
    try {
      keychainRemoved = deleteAgentAuthTokenImpl(agentKeyId);
    } catch (error) {
      keychainError = renderError(error);
    }
  }

  let configDeleted = false;
  /* c8 ignore next -- configExists implies readConfigImpl() returned an object in this module; nullish fallback is defensive */
  let configValue: Record<string, unknown> | null = configExists ? redactConfig(currentConfig ?? {}) : null;
  if (options.deleteConfig) {
    if (configExists) {
      unlinkSyncImpl(configPath);
      configDeleted = true;
      configValue = null;
    }
  } else if (configExists) {
    if (clearedAgentKeyId) {
      deleteConfigKeyImpl('agentKeyId');
    }
    if (clearedLegacyAgentAuthToken) {
      deleteConfigKeyImpl('agentAuthToken');
    }
    if (clearedWalletMetadata) {
      deleteConfigKeyImpl('wallet');
    }
    configValue = redactConfig(readConfigImpl());
  }

  let bootstrapArtifacts: CleanupLocalAdminResetStateResult['bootstrapArtifacts'];
  if (!existsSync(agentpayHome)) {
    bootstrapArtifacts = {
      attempted: false,
      action: 'deleted',
      fileCount: 0,
      cleanedCount: 0,
      skippedCount: 0,
      error: null,
    };
  } else {
    try {
      const cleanup = cleanupBootstrapArtifactsImpl('deleted');
      bootstrapArtifacts = {
        attempted: true,
        action: 'deleted',
        fileCount: cleanup.files.length,
        cleanedCount: cleanup.files.filter((file) => file.cleanup === 'deleted').length,
        skippedCount: cleanup.files.filter((file) => file.cleanup === 'skipped').length,
        error: null,
      };
    } catch (error) {
      bootstrapArtifacts = {
        attempted: true,
        action: 'deleted',
        fileCount: 0,
        cleanedCount: 0,
        skippedCount: 0,
        error: renderError(error),
      };
    }
  }

  return {
    agentKeyId,
    keychain: {
      removed: keychainRemoved,
      service: resolveAgentAuthStorageService(platform, agentKeyId ?? undefined),
      error: keychainError,
    },
    config: {
      path: configPath,
      existed: configExists,
      deleted: configDeleted,
      clearedAgentKeyId,
      clearedLegacyAgentAuthToken,
      clearedWalletMetadata,
      value: configValue,
    },
    bootstrapArtifacts,
  };
}

function isPathInside(parentPath: string, childPath: string): boolean {
  const relative = path.relative(path.resolve(parentPath), path.resolve(childPath));
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}

function normalizeInstallerPathList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .filter((entry): entry is string => typeof entry === 'string')
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);
}

function resolveOneClickInstallManifestPath(agentpayHome: string): string {
  return path.join(agentpayHome, ONE_CLICK_INSTALL_MANIFEST_FILENAME);
}

function readOneClickInstallManifest(
  manifestPath: string,
  deps: Pick<CleanupLocalAdminUninstallStateDeps, 'existsSync' | 'readFileSync'>,
): {
  manifest: OneClickInstallManifest | null;
  existed: boolean;
  warning: string | null;
} {
  const existsSync = deps.existsSync ?? fs.existsSync;
  const readFileSyncImpl = deps.readFileSync ?? fs.readFileSync;

  if (!existsSync(manifestPath)) {
    return {
      manifest: null,
      existed: false,
      warning: null,
    };
  }

  try {
    const parsed = JSON.parse(readFileSyncImpl(manifestPath, 'utf8')) as Record<string, unknown>;
    return {
      manifest: {
        version: typeof parsed.version === 'number' ? parsed.version : undefined,
        installRoot: typeof parsed.installRoot === 'string' ? parsed.installRoot.trim() : undefined,
        agentpayHome: typeof parsed.agentpayHome === 'string' ? parsed.agentpayHome.trim() : undefined,
        shellRcPath:
          typeof parsed.shellRcPath === 'string' ? parsed.shellRcPath.trim() : undefined,
        skillTargets: normalizeInstallerPathList(parsed.skillTargets),
        cursorArtifactPaths: normalizeInstallerPathList(parsed.cursorArtifactPaths),
        pathShimPaths: normalizeInstallerPathList(parsed.pathShimPaths),
      },
      existed: true,
      warning: null,
    };
  } catch (error) {
    return {
      manifest: null,
      existed: true,
      warning: `ignoring unreadable one-click install manifest at ${manifestPath}: ${renderError(error)}`,
    };
  }
}

function removeInstallerRcBlock(
  targetPath: string,
  deps: Pick<CleanupLocalAdminUninstallStateDeps, 'existsSync' | 'readFileSync' | 'writeFileSync'>,
): boolean {
  const existsSync = deps.existsSync ?? fs.existsSync;
  const readFileSyncImpl = deps.readFileSync ?? fs.readFileSync;
  const writeFileSyncImpl = deps.writeFileSync ?? fs.writeFileSync;

  if (!existsSync(targetPath)) {
    return false;
  }

  const original = readFileSyncImpl(targetPath, 'utf8');
  if (!original.includes(ONE_CLICK_RC_BLOCK_START)) {
    return false;
  }

  const lines = original.split(/\r?\n/u);
  const nextLines: string[] = [];
  let skipping = false;
  let removed = false;

  for (const line of lines) {
    if (line === ONE_CLICK_RC_BLOCK_START) {
      skipping = true;
      removed = true;
      continue;
    }
    if (line === ONE_CLICK_RC_BLOCK_END) {
      skipping = false;
      continue;
    }
    if (!skipping) {
      nextLines.push(line);
    }
  }

  if (!removed) {
    return false;
  }

  while (nextLines.length > 0 && nextLines[nextLines.length - 1] === '') {
    nextLines.pop();
  }
  const next = nextLines.length > 0 ? `${nextLines.join('\n')}\n` : '';
  writeFileSyncImpl(targetPath, next, 'utf8');
  return true;
}

function removeExistingPath(
  targetPath: string,
  deps: Pick<CleanupLocalAdminUninstallStateDeps, 'existsSync' | 'rmSync'>,
): boolean {
  const existsSync = deps.existsSync ?? fs.existsSync;
  const rmSyncImpl = deps.rmSync ?? fs.rmSync;
  if (!existsSync(targetPath)) {
    return false;
  }
  rmSyncImpl(targetPath, { recursive: true, force: true });
  return true;
}

function removeManagedPathShim(
  targetPath: string,
  deps: Pick<
    CleanupLocalAdminUninstallStateDeps,
    'existsSync' | 'readFileSync' | 'rmSync'
  >,
): boolean {
  const existsSync = deps.existsSync ?? fs.existsSync;
  const readFileSyncImpl = deps.readFileSync ?? fs.readFileSync;
  const rmSyncImpl = deps.rmSync ?? fs.rmSync;

  if (!existsSync(targetPath)) {
    return false;
  }

  try {
    const contents = readFileSyncImpl(targetPath, 'utf8');
    if (!contents.includes(ONE_CLICK_PATH_SHIM_MARKER)) {
      return false;
    }
  } catch {
    return false;
  }

  rmSyncImpl(targetPath, { recursive: true, force: true });
  return true;
}

function pruneEmptyCursorParents(
  targetPath: string,
  deps: Pick<CleanupLocalAdminUninstallStateDeps, 'existsSync' | 'readdirSync' | 'rmSync'>,
): void {
  const existsSync = deps.existsSync ?? fs.existsSync;
  const readdirSyncImpl = deps.readdirSync ?? fs.readdirSync;
  const rmSyncImpl = deps.rmSync ?? fs.rmSync;

  let current = path.dirname(targetPath);
  while (true) {
    const currentName = path.basename(current);
    if (currentName !== 'rules' && currentName !== '.cursor') {
      return;
    }
    if (!existsSync(current)) {
      current = path.dirname(current);
      continue;
    }
    const entries = readdirSyncImpl(current);
    if (entries.length > 0) {
      return;
    }
    rmSyncImpl(current, { recursive: true, force: true });
    current = path.dirname(current);
  }
}

function resolveKnownOneClickSkillTargets(homeDir: string): string[] {
  return [
    path.join(homeDir, '.codex', 'skills', 'agentpay-sdk'),
    path.join(homeDir, '.agents', 'skills', 'agentpay-sdk'),
    path.join(homeDir, '.openclaw', 'skills', 'agentpay-sdk'),
    path.join(homeDir, '.claude', 'skills', 'agentpay-sdk'),
  ];
}

function inferOneClickInstallRoot(
  manifest: OneClickInstallManifest | null,
  agentpayHome: string,
): string | null {
  const manifestInstallRoot = manifest?.installRoot?.trim();
  if (manifestInstallRoot) {
    return manifestInstallRoot;
  }
  if (path.basename(agentpayHome) === 'agentpay-home') {
    return path.dirname(agentpayHome);
  }
  return null;
}

export function cleanupLocalAdminUninstallState(
  deps: CleanupLocalAdminUninstallStateDeps = {},
): CleanupLocalAdminUninstallStateResult {
  const platform = deps.platform ?? process.platform;
  const existsSync = deps.existsSync ?? fs.existsSync;
  const resolveConfigPathImpl = deps.resolveConfigPath ?? resolveConfigPath;
  const resolveAgentPayHomeImpl = deps.resolveAgentPayHome ?? resolveAgentPayHome;
  const readConfigImpl = deps.readConfig ?? readConfig;
  const deleteAgentAuthTokenImpl =
    deps.deleteAgentAuthToken ??
    ((agentKeyId: string) => deleteStoredAgentAuthToken(agentKeyId, platform));
  const rmSyncImpl = deps.rmSync ?? fs.rmSync;
  const homedirImpl = deps.homedir ?? os.homedir;
  const readdirSyncImpl = deps.readdirSync ?? fs.readdirSync;

  const configPath = resolveConfigPathImpl();
  const agentpayHome = resolveAgentPayHomeImpl();
  const manifestPath = resolveOneClickInstallManifestPath(agentpayHome);
  const manifestRecord = readOneClickInstallManifest(manifestPath, deps);
  const configExists = existsSync(configPath);
  const agentpayHomeExists = existsSync(agentpayHome);
  const currentConfig = configExists ? readConfigImpl() : null;
  const agentKeyId = currentConfig?.agentKeyId ?? null;
  let keychainRemoved = false;
  let keychainError: string | null = null;
  if (agentKeyId) {
    try {
      keychainRemoved = deleteAgentAuthTokenImpl(agentKeyId);
    } catch (error) {
      keychainError = renderError(error);
    }
  }
  const shellRcCandidates = new Set<string>();
  const knownSkillTargets = resolveKnownOneClickSkillTargets(homedirImpl());
  const skillTargetsRemoved: string[] = [];
  const cursorArtifactsRemoved: string[] = [];
  const pathShimsRemoved: string[] = [];
  const shellRcFilesUpdated: string[] = [];

  for (const rcPath of [manifestRecord.manifest?.shellRcPath, path.join(homedirImpl(), '.zshrc'), path.join(homedirImpl(), '.bashrc')]) {
    if (typeof rcPath === 'string' && rcPath.trim().length > 0) {
      shellRcCandidates.add(path.resolve(rcPath));
    }
  }

  const skillTargets = new Set<string>();
  for (const targetPath of knownSkillTargets) {
    skillTargets.add(path.resolve(targetPath));
  }
  for (const targetPath of manifestRecord.manifest?.skillTargets ?? []) {
    skillTargets.add(path.resolve(targetPath));
  }

  const cursorArtifactTargets = new Set<string>();
  for (const targetPath of manifestRecord.manifest?.cursorArtifactPaths ?? []) {
    cursorArtifactTargets.add(path.resolve(targetPath));
  }

  const pathShimTargets = new Set<string>();
  for (const targetPath of manifestRecord.manifest?.pathShimPaths ?? []) {
    pathShimTargets.add(path.resolve(targetPath));
  }

  let configDeleted = false;
  if (configExists && (!agentpayHomeExists || !isPathInside(agentpayHome, configPath))) {
    rmSyncImpl(configPath, { recursive: true, force: true });
    configDeleted = true;
  } else if (configExists && agentpayHomeExists) {
    configDeleted = true;
  }

  let agentpayHomeDeleted = false;
  if (agentpayHomeExists) {
    rmSyncImpl(agentpayHome, { recursive: true, force: true });
    agentpayHomeDeleted = true;
  }

  for (const rcPath of shellRcCandidates) {
    if (removeInstallerRcBlock(rcPath, deps)) {
      shellRcFilesUpdated.push(rcPath);
    }
  }

  for (const targetPath of skillTargets) {
    if (removeExistingPath(targetPath, deps)) {
      skillTargetsRemoved.push(targetPath);
    }
  }

  for (const targetPath of cursorArtifactTargets) {
    if (removeExistingPath(targetPath, deps)) {
      cursorArtifactsRemoved.push(targetPath);
      pruneEmptyCursorParents(targetPath, deps);
    }
  }

  for (const targetPath of pathShimTargets) {
    if (removeManagedPathShim(targetPath, deps)) {
      pathShimsRemoved.push(targetPath);
    }
  }

  const installRootPath = inferOneClickInstallRoot(manifestRecord.manifest, agentpayHome);
  let installRootRemoved = false;
  let installRootSkippedReason: string | null = null;
  if (!installRootPath) {
    installRootSkippedReason = 'one-click install root was not recorded';
  } else if (path.resolve(installRootPath) === path.resolve(agentpayHome) && agentpayHomeDeleted) {
    installRootRemoved = true;
  } else if (!existsSync(installRootPath)) {
    installRootSkippedReason = 'one-click install root was already absent';
  } else {
    const remainingEntries = readdirSyncImpl(installRootPath);
    if (remainingEntries.length === 0) {
      rmSyncImpl(installRootPath, { recursive: true, force: true });
      installRootRemoved = true;
    } else {
      installRootSkippedReason = 'one-click install root still contains files';
    }
  }

  return {
    agentKeyId,
    keychain: {
      removed: keychainRemoved,
      service: resolveAgentAuthStorageService(platform, agentKeyId ?? undefined),
      error: keychainError,
    },
    config: {
      path: configPath,
      existed: configExists,
      deleted: configDeleted,
    },
    agentpayHome: {
      path: agentpayHome,
      existed: agentpayHomeExists,
      deleted: agentpayHomeDeleted,
    },
    oneClickInstaller: {
      manifest: {
        path: manifestPath,
        existed: manifestRecord.existed,
        removedWithAgentPayHome: manifestRecord.existed && agentpayHomeDeleted,
        warning: manifestRecord.warning,
      },
      shellRcFilesUpdated,
      skillTargetsRemoved,
      cursorArtifactsRemoved,
      pathShimsRemoved,
      installRoot: {
        path: installRootPath,
        removed: installRootRemoved,
        skippedReason: installRootSkippedReason,
      },
    },
  };
}

async function confirmReset(options: AdminResetOptions): Promise<void> {
  if (options.yes) {
    return;
  }
  if (options.nonInteractive) {
    throw new Error('`agentpay admin reset` requires --yes in non-interactive mode');
  }

  process.stderr.write(
    'warning: admin reset permanently deletes the managed daemon state and the current wallet; if you do not have an external backup, the old address is lost forever.\n',
  );
  const confirmation = await promptVisible(
    'Type RESET to delete the managed daemon state and local wallet credentials: ',
  );
  if (confirmation !== 'RESET') {
    throw new Error('admin reset aborted');
  }
}

async function runAdminReset(options: AdminResetOptions): Promise<void> {
  assertManagedDaemonPlatform(
    '`agentpay admin reset`',
    'The current reset flow uninstalls the root-managed daemon and deletes managed daemon state.',
  );

  assertNotInvokedViaSudo('admin reset');
  await confirmReset(options);
  const showProgress = !options.json;
  const keychainAccount = os.userInfo().username;

  if (!options.json && typeof process.geteuid === 'function' && process.geteuid() !== 0) {
    process.stderr.write(
      'System admin password required: reset uses sudo to uninstall the root-managed daemon and delete its state.\n',
    );
  }
  await sudoSession.prime();
  const currentConfig = readConfigIfPresent();

  const uninstallProgress = createProgress('Uninstalling managed daemon', showProgress);
  let uninstallResult;
  try {
    uninstallResult = await sudoSession.run(
      process.platform === 'linux'
        ? [
            resolveLaunchDaemonUninstallScriptPath(currentConfig),
            '--label',
            DEFAULT_LAUNCH_DAEMON_LABEL,
            ...(MANAGED_DAEMON_SPEC.daemonPasswordFile
              ? ['--delete-password-file', MANAGED_DAEMON_SPEC.daemonPasswordFile]
              : []),
          ]
        : [
            resolveLaunchDaemonUninstallScriptPath(currentConfig),
            '--label',
            DEFAULT_LAUNCH_DAEMON_LABEL,
            '--keychain-service',
            DAEMON_PASSWORD_KEYCHAIN_SERVICE,
            '--keychain-account',
            keychainAccount,
            '--delete-keychain-password',
          ],
    );
    /* c8 ignore next 4 -- sudoSession.run reports command failures via exit codes; synchronous throws are defensive */
  } catch (error) {
    uninstallProgress.fail();
    throw error;
  }
  if (uninstallResult.code !== 0) {
    uninstallProgress.fail();
    throw new Error(
      uninstallResult.stderr.trim()
        || uninstallResult.stdout.trim()
        || `failed to uninstall managed daemon (exit code ${uninstallResult.code})`,
    );
  }
  uninstallProgress.succeed('Managed daemon uninstalled');

  const stateProgress = createProgress('Deleting root-managed daemon state', showProgress);
  let deleteRootArtifactsResult;
  try {
    deleteRootArtifactsResult = await sudoSession.run([
      '/bin/rm',
      '-f',
      ...managedDaemonResetArtifactPaths(),
    ]);
    /* c8 ignore next 4 -- sudoSession.run reports command failures via exit codes; synchronous throws are defensive */
  } catch (error) {
    stateProgress.fail();
    throw error;
  }
  if (deleteRootArtifactsResult.code !== 0) {
    stateProgress.fail();
    throw new Error(
      deleteRootArtifactsResult.stderr.trim()
        || deleteRootArtifactsResult.stdout.trim()
        || `failed to delete managed daemon state (exit code ${deleteRootArtifactsResult.code})`,
    );
  }
  stateProgress.succeed('Root-managed daemon state deleted');

  const localProgress = createProgress('Removing local wallet credentials', showProgress);
  let local: CleanupLocalAdminResetStateResult;
  try {
    local = cleanupLocalAdminResetState({ deleteConfig: options.deleteConfig });
    localProgress.succeed('Local wallet credentials removed');
  } catch (error) {
    localProgress.fail();
    throw error;
  }

  const result = {
    command: 'reset',
    daemon: {
      autostart: false,
      label: DEFAULT_LAUNCH_DAEMON_LABEL,
      serviceManager: MANAGED_DAEMON_SPEC.serviceManager,
      serviceFile: DEFAULT_LAUNCH_DAEMON_PLIST,
      daemonSocket: DEFAULT_MANAGED_DAEMON_SOCKET,
      relayDaemonTokenFile: DEFAULT_MANAGED_RELAY_DAEMON_TOKEN_FILE,
      stateFile: DEFAULT_MANAGED_STATE_FILE,
      systemKeychainPasswordService: MANAGED_DAEMON_SPEC.daemonPasswordService,
      systemKeychainPasswordAccount: process.platform === 'darwin' ? keychainAccount : null,
      daemonPasswordFile: MANAGED_DAEMON_SPEC.daemonPasswordFile,
    },
    local,
    nextStep: 'Run `agentpay admin setup` to create a new wallet and re-install the managed daemon.',
  };

  if (options.json) {
    print(result, true);
    return;
  }

  printResetSummary({
    daemon: {
      label: result.daemon.label,
      daemonSocket: result.daemon.daemonSocket,
      relayDaemonTokenFile: result.daemon.relayDaemonTokenFile,
      stateFile: result.daemon.stateFile,
    },
    local,
  });
}

async function confirmUninstall(options: AdminUninstallOptions): Promise<void> {
  if (options.yes) {
    return;
  }
  if (options.nonInteractive) {
    throw new Error('`agentpay admin uninstall` requires --yes in non-interactive mode');
  }

  process.stderr.write(
    'warning: admin uninstall permanently removes the managed daemon, root-managed state, local wallet config, local binaries, and logs.\n',
  );
  const confirmation = await promptVisible(
    'Type UNINSTALL to delete all AgentPay managed files and local credentials: ',
  );
  if (confirmation !== 'UNINSTALL') {
    throw new Error('admin uninstall aborted');
  }
}

function printUninstallSummary(result: {
  daemon: {
    label: string;
    daemonRoot: string;
    stateDir: string;
    logDir: string | null;
  };
  local: CleanupLocalAdminUninstallStateResult;
  globalCli: GlobalCliUninstallResult;
}): void {
  const lines = [
    'uninstall complete',
    `managed daemon removed: ${result.daemon.label}`,
    `managed daemon files removed: ${result.daemon.daemonRoot}`,
    `managed state directory removed: ${result.daemon.stateDir}`,
    ...(result.daemon.logDir ? [`managed log directory removed: ${result.daemon.logDir}`] : []),
    result.local.agentKeyId
      ? `old agent key cleared: ${result.local.agentKeyId}`
      : 'old agent key cleared: no configured agent key was found',
    /* c8 ignore start -- public uninstall summary only reaches here when a AgentPay home existed or config provided the helper paths */
    result.local.agentpayHome.existed
      ? `local AgentPay home removed: ${result.local.agentpayHome.path}`
      : `local AgentPay home not found: ${result.local.agentpayHome.path}`,
    /* c8 ignore stop */
    result.local.config.existed
      ? `config removed: ${result.local.config.path}`
      : `config not found: ${result.local.config.path}`,
  ];
  if (result.local.keychain.error) {
    lines.push(`local credential cleanup warning: ${result.local.keychain.error}`);
  }

  for (const rcPath of result.local.oneClickInstaller.shellRcFilesUpdated) {
    lines.push(`shell rc cleaned: ${rcPath}`);
  }
  for (const targetPath of result.local.oneClickInstaller.skillTargetsRemoved) {
    lines.push(`AI skill removed: ${targetPath}`);
  }
  for (const targetPath of result.local.oneClickInstaller.cursorArtifactsRemoved) {
    lines.push(`Cursor adapter removed: ${targetPath}`);
  }
  for (const targetPath of result.local.oneClickInstaller.pathShimsRemoved) {
    lines.push(`PATH shim removed: ${targetPath}`);
  }
  if (result.local.oneClickInstaller.installRoot.removed && result.local.oneClickInstaller.installRoot.path) {
    lines.push(`one-click install root removed: ${result.local.oneClickInstaller.installRoot.path}`);
  }
  if (result.local.oneClickInstaller.manifest.warning) {
    lines.push(`one-click cleanup warning: ${result.local.oneClickInstaller.manifest.warning}`);
  }

  if (result.globalCli.removed) {
    lines.push(`${LEGACY_GLOBAL_NPM_CLI_LABEL} removed`);
    if (result.globalCli.installPath) {
      lines.push(`legacy global npm package removed from: ${result.globalCli.installPath}`);
    }
    lines.push(
      'next: reinstall with `curl -fsSL https://wlfi.sh | bash` or use the repo source install steps, then run `agentpay admin setup` only if you want a fresh managed wallet again',
    );
  } else {
    lines.push(
      `${LEGACY_GLOBAL_NPM_CLI_LABEL} not removed: ${result.globalCli.skippedReason ?? 'no matching legacy global npm install was detected'}`,
    );
    lines.push('next: run `agentpay admin setup` only if you want a fresh managed wallet again');
  }
  console.log(lines.join('\n'));
}

async function runAdminUninstall(options: AdminUninstallOptions): Promise<void> {
  assertManagedDaemonPlatform(
    '`agentpay admin uninstall`',
    'The current uninstall flow removes the root-managed daemon and managed daemon files.',
  );

  assertNotInvokedViaSudo('admin uninstall');
  await confirmUninstall(options);
  const showProgress = !options.json;
  const keychainAccount = os.userInfo().username;

  if (!options.json && typeof process.geteuid === 'function' && process.geteuid() !== 0) {
    process.stderr.write(
      'System admin password required: uninstall uses sudo to remove the root-managed daemon and all managed root-owned files.\n',
    );
  }
  await sudoSession.prime();
  const currentConfig = readConfigIfPresent();

  const uninstallProgress = createProgress('Uninstalling managed daemon', showProgress);
  let uninstallResult;
  try {
    uninstallResult = await sudoSession.run(
      process.platform === 'linux'
        ? [
            resolveLaunchDaemonUninstallScriptPath(currentConfig),
            '--label',
            DEFAULT_LAUNCH_DAEMON_LABEL,
            ...(MANAGED_DAEMON_SPEC.daemonPasswordFile
              ? ['--delete-password-file', MANAGED_DAEMON_SPEC.daemonPasswordFile]
              : []),
          ]
        : [
            resolveLaunchDaemonUninstallScriptPath(currentConfig),
            '--label',
            DEFAULT_LAUNCH_DAEMON_LABEL,
            '--keychain-service',
            DAEMON_PASSWORD_KEYCHAIN_SERVICE,
            '--keychain-account',
            keychainAccount,
            '--delete-keychain-password',
          ],
    );
    /* c8 ignore next 4 -- sudoSession.run reports command failures via exit codes; synchronous throws are defensive */
  } catch (error) {
    uninstallProgress.fail();
    throw error;
  }
  if (uninstallResult.code !== 0) {
    uninstallProgress.fail();
    throw new Error(
      uninstallResult.stderr.trim()
        || uninstallResult.stdout.trim()
        || `failed to uninstall managed daemon (exit code ${uninstallResult.code})`,
    );
  }
  uninstallProgress.succeed('Managed daemon uninstalled');

  const rootProgress = createProgress('Removing managed root-owned files', showProgress);
  let deleteRootArtifactsResult;
  try {
    const rootPaths = [
      DEFAULT_MANAGED_ROOT_DIR,
      DEFAULT_MANAGED_STATE_DIR,
      ...(DEFAULT_MANAGED_LOG_DIR ? [DEFAULT_MANAGED_LOG_DIR] : []),
    ];
    deleteRootArtifactsResult = await sudoSession.run(['/bin/rm', '-rf', ...rootPaths]);
    /* c8 ignore next 4 -- sudoSession.run reports command failures via exit codes; synchronous throws are defensive */
  } catch (error) {
    rootProgress.fail();
    throw error;
  }
  if (deleteRootArtifactsResult.code !== 0) {
    rootProgress.fail();
    throw new Error(
      deleteRootArtifactsResult.stderr.trim()
        || deleteRootArtifactsResult.stdout.trim()
        || `failed to delete managed root-owned files (exit code ${deleteRootArtifactsResult.code})`,
    );
  }
  try {
    await assertManagedUninstallArtifactsRemoved([
      DEFAULT_LAUNCH_DAEMON_PLIST,
      DEFAULT_MANAGED_ROOT_DIR,
      DEFAULT_MANAGED_STATE_DIR,
      ...(DEFAULT_MANAGED_LOG_DIR ? [DEFAULT_MANAGED_LOG_DIR] : []),
    ]);
    rootProgress.succeed('Managed root-owned files removed');
  } catch (error) {
    rootProgress.fail();
    throw error;
  }

  const localProgress = createProgress('Removing local AgentPay files and credentials', showProgress);
  let local: CleanupLocalAdminUninstallStateResult;
  try {
    local = cleanupLocalAdminUninstallState();
    assertLocalUninstallArtifactsRemoved(local);
    localProgress.succeed('Local AgentPay files and credentials removed');
  } catch (error) {
    localProgress.fail();
    throw error;
  }

  let globalCli: GlobalCliUninstallResult = {
    packageName: GLOBAL_NPM_CLI_PACKAGE_NAME,
    packageManager: 'npm',
    attempted: false,
    removed: false,
    installPath: null,
    skippedReason: 'current command is not running from a legacy global npm install',
  };
  const globalCliProgress = createProgress(`Removing ${LEGACY_GLOBAL_NPM_CLI_LABEL}`, showProgress);
  try {
    globalCli = uninstallCurrentGlobalNpmCli();
    globalCliProgress.succeed(
      globalCli.removed
        ? `${LEGACY_GLOBAL_NPM_CLI_LABEL} removed`
        : `${LEGACY_GLOBAL_NPM_CLI_LABEL} removal not needed`,
    );
  } catch (error) {
    globalCliProgress.fail();
    throw error;
  }

  const result = {
    command: 'uninstall',
    daemon: {
      autostart: false,
      label: DEFAULT_LAUNCH_DAEMON_LABEL,
      serviceManager: MANAGED_DAEMON_SPEC.serviceManager,
      serviceFile: DEFAULT_LAUNCH_DAEMON_PLIST,
      daemonSocket: DEFAULT_MANAGED_DAEMON_SOCKET,
      stateFile: DEFAULT_MANAGED_STATE_FILE,
      daemonRoot: DEFAULT_MANAGED_ROOT_DIR,
      stateDir: DEFAULT_MANAGED_STATE_DIR,
      logDir: DEFAULT_MANAGED_LOG_DIR || null,
      systemKeychainPasswordService: MANAGED_DAEMON_SPEC.daemonPasswordService,
      systemKeychainPasswordAccount: process.platform === 'darwin' ? keychainAccount : null,
      daemonPasswordFile: MANAGED_DAEMON_SPEC.daemonPasswordFile,
    },
    local,
    globalCli,
    nextStep: globalCli.removed
      ? 'Reinstall with `curl -fsSL https://wlfi.sh | bash` or use the repo source install steps, then run `agentpay admin setup` to create a fresh managed wallet again.'
      : 'Run `agentpay admin setup` only if you want a fresh managed wallet again.',
  };

  if (options.json) {
    print(result, true);
    return;
  }

  printUninstallSummary({
    daemon: {
      label: result.daemon.label,
      daemonRoot: result.daemon.daemonRoot,
      stateDir: result.daemon.stateDir,
      logDir: result.daemon.logDir,
    },
    local,
    globalCli,
  });
}

export async function runAdminResetCli(argv: string[]): Promise<void> {
  const program = new Command();
  program
    .name('agentpay admin reset')
    .description(
      'Delete the root-managed daemon state and local wallet credentials so a fresh wallet can be set up',
    )
    .option('-y, --yes', 'Skip the destructive confirmation prompt', false)
    .option('--non-interactive', 'Disable confirmation prompts; requires --yes', false)
    .option(
      '--delete-config',
      'Delete ~/.agentpay/config.json instead of only clearing wallet-specific credentials',
      false,
    )
    .option('--json', 'Print JSON output', false)
    .action(runAdminReset);

  await program.parseAsync(argv, { from: 'user' });
}

export async function runAdminUninstallCli(argv: string[]): Promise<void> {
  const program = new Command();
  program
    .name('agentpay admin uninstall')
    .description(
      'Fully remove the managed daemon, local AgentPay state, and the global npm-installed agentpay CLI when this command is run from that install',
    )
    .option('-y, --yes', 'Skip the destructive confirmation prompt', false)
    .option('--non-interactive', 'Disable confirmation prompts; requires --yes', false)
    .option('--json', 'Print JSON output', false)
    .action(runAdminUninstall);

  await program.parseAsync(argv, { from: 'user' });
}
