import fs from 'node:fs';
import path from 'node:path';
import { resolveAgentPayHome } from '../../packages/config/src/index.js';
import {
  assertBootstrapSetupSummaryLeaseIsActive,
  cleanupBootstrapAgentCredentialsFile,
  readBootstrapAgentCredentialsFile,
  readBootstrapSetupSummaryFile,
} from './bootstrap-credentials.js';
import { assertTrustedDirectoryPath, assertTrustedPrivateFilePath } from './fs-trust.js';

const AUTO_GENERATED_BOOTSTRAP_FILE_PATTERN = /^bootstrap-\d+-\d+\.json$/u;
const MAX_AUTO_GENERATED_BOOTSTRAP_FILES = 128;

export type BootstrapArtifactStatus = 'plaintext' | 'redacted' | 'invalid' | 'untrusted';

export interface BootstrapArtifactCheck {
  path: string;
  status: BootstrapArtifactStatus;
  agentKeyId: string | null;
  leaseExpiresAt: string | null;
  leaseExpired: boolean;
  error: string | null;
}

export interface CleanupBootstrapArtifactResult extends BootstrapArtifactCheck {
  cleanup: 'deleted' | 'redacted' | 'skipped' | 'failed';
}

export interface CleanupBootstrapArtifactsResult {
  agentpayHome: string;
  action: 'deleted' | 'redacted';
  files: CleanupBootstrapArtifactResult[];
}

interface BootstrapArtifactsDeps {
  resolveAgentPayHome?: () => string;
  readdirSync?: typeof fs.readdirSync;
}

function renderError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function resolveAutoGeneratedBootstrapPaths(
  agentpayHome: string,
  deps: BootstrapArtifactsDeps = {},
): string[] {
  const readdirSync = deps.readdirSync ?? fs.readdirSync;
  const resolvedHome = path.resolve(agentpayHome);
  try {
    assertTrustedDirectoryPath(resolvedHome, 'AgentPay home');
  } catch {
    return [];
  }

  let entries: fs.Dirent[];
  try {
    entries = readdirSync(resolvedHome, { withFileTypes: true }) as fs.Dirent[];
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return [];
    }
    throw error;
  }

  return entries
    .filter((entry) => AUTO_GENERATED_BOOTSTRAP_FILE_PATTERN.test(entry.name))
    .map((entry) => path.join(resolvedHome, entry.name))
    .sort((left, right) => right.localeCompare(left))
    .slice(0, MAX_AUTO_GENERATED_BOOTSTRAP_FILES);
}

export function inspectBootstrapArtifact(targetPath: string): BootstrapArtifactCheck {
  const resolvedPath = path.resolve(targetPath);

  try {
    assertTrustedPrivateFilePath(resolvedPath, 'bootstrap file');
  } catch (error) {
    return {
      path: resolvedPath,
      status: 'untrusted',
      agentKeyId: null,
      leaseExpiresAt: null,
      leaseExpired: false,
      error: renderError(error),
    };
  }

  let summary: ReturnType<typeof readBootstrapSetupSummaryFile>;
  try {
    summary = readBootstrapSetupSummaryFile(resolvedPath);
  } catch (error) {
    return {
      path: resolvedPath,
      status: 'invalid',
      agentKeyId: null,
      leaseExpiresAt: null,
      leaseExpired: false,
      error: renderError(error),
    };
  }

  let leaseExpired = false;
  try {
    assertBootstrapSetupSummaryLeaseIsActive(summary);
  } catch (error) {
    const message = renderError(error);
    if (message.includes('lease has expired')) {
      leaseExpired = true;
    } else {
      return {
        path: resolvedPath,
        status: 'invalid',
        agentKeyId: summary.agentKeyId,
        leaseExpiresAt: summary.leaseExpiresAt,
        leaseExpired: false,
        error: message,
      };
    }
  }

  try {
    const credentials = readBootstrapAgentCredentialsFile(resolvedPath);
    return {
      path: resolvedPath,
      status: 'plaintext',
      agentKeyId: credentials.agentKeyId,
      leaseExpiresAt: summary.leaseExpiresAt,
      leaseExpired,
      error: null,
    };
  } catch (error) {
    const message = renderError(error);
    if (message.includes('contains a redacted agent auth token')) {
      if (summary.vaultPrivateKey !== null) {
        return {
          path: resolvedPath,
          status: 'plaintext',
          agentKeyId: summary.agentKeyId,
          leaseExpiresAt: summary.leaseExpiresAt,
          leaseExpired,
          error: null,
        };
      }
      return {
        path: resolvedPath,
        status: 'redacted',
        agentKeyId: summary.agentKeyId,
        leaseExpiresAt: summary.leaseExpiresAt,
        leaseExpired,
        error: null,
      };
    }

    return {
      path: resolvedPath,
      status: 'invalid',
      agentKeyId: summary.agentKeyId,
      leaseExpiresAt: summary.leaseExpiresAt,
      leaseExpired,
      error: message,
    };
  }
}

export function listAutoGeneratedBootstrapArtifacts(
  deps: BootstrapArtifactsDeps = {},
): BootstrapArtifactCheck[] {
  const agentpayHome = (deps.resolveAgentPayHome ?? resolveAgentPayHome)();
  return resolveAutoGeneratedBootstrapPaths(agentpayHome, deps).map((targetPath) =>
    inspectBootstrapArtifact(targetPath),
  );
}

export function cleanupAutoGeneratedBootstrapArtifacts(
  action: 'deleted' | 'redacted' = 'deleted',
  deps: BootstrapArtifactsDeps = {},
): CleanupBootstrapArtifactsResult {
  const agentpayHome = path.resolve((deps.resolveAgentPayHome ?? resolveAgentPayHome)());
  assertTrustedDirectoryPath(agentpayHome, 'AgentPay home');

  const files = resolveAutoGeneratedBootstrapPaths(agentpayHome, deps).map((targetPath) => {
    const artifact = inspectBootstrapArtifact(targetPath);
    if (artifact.status !== 'plaintext' && artifact.status !== 'redacted') {
      return {
        ...artifact,
        cleanup: 'skipped' as const,
      };
    }

    const result = cleanupBootstrapAgentCredentialsFile(targetPath, action);
    if (result.action === 'failed') {
      return {
        ...artifact,
        path: result.sourcePath,
        cleanup: 'failed' as const,
        error: result.error,
      };
    }

    const cleanup = result.action === 'missing' ? ('skipped' as const) : result.action;

    return {
      ...artifact,
      path: result.sourcePath,
      cleanup,
    };
  });

  return {
    agentpayHome,
    action,
    files,
  };
}
