import {
  type WlfiConfig,
  writeConfig,
} from '../../packages/config/src/index.js';
import { resolveAdminSetupVaultPassword } from './admin-setup.js';
import { deleteBootstrapAgentCredentialsFile } from './bootstrap-credentials.js';
import { resolveValidatedAdminDaemonSocket } from './admin-daemon-socket.js';
import { supportsManagedDaemonPlatform } from './platform-support.js';
import { runRustBinary } from './rust.js';
import {
  buildWalletSetupAdminArgs,
  completeWalletSetup,
  resolveWalletSetupBootstrapOutputPath,
  resolveWalletSetupCleanupAction,
} from './wallet-setup.js';

export interface SharedConfigWalletApplyOptions {
  daemonSocket?: string;
  vaultPasswordStdin?: boolean;
  nonInteractive?: boolean;
}

export interface SharedConfigWalletApplyResult {
  applied: boolean;
  daemonSocket?: string;
  walletSetup?: ReturnType<typeof completeWalletSetup>;
}

interface SharedConfigWalletApplyDeps {
  platform?: NodeJS.Platform;
  resolveValidatedAdminDaemonSocket?: typeof resolveValidatedAdminDaemonSocket;
  resolveAdminSetupVaultPassword?: typeof resolveAdminSetupVaultPassword;
  resolveWalletSetupBootstrapOutputPath?: typeof resolveWalletSetupBootstrapOutputPath;
  resolveWalletSetupCleanupAction?: typeof resolveWalletSetupCleanupAction;
  buildWalletSetupAdminArgs?: typeof buildWalletSetupAdminArgs;
  runRustBinary?: typeof runRustBinary;
  completeWalletSetup?: typeof completeWalletSetup;
  writeConfig?: typeof writeConfig;
  deleteBootstrapAgentCredentialsFile?: typeof deleteBootstrapAgentCredentialsFile;
}

function presentString(value: string | undefined): string | null {
  const normalized = value?.trim();
  return normalized ? normalized : null;
}

function hasExistingWalletApplyTarget(config: WlfiConfig): boolean {
  const wallet = config.wallet;
  return Boolean(
    presentString(wallet?.vaultKeyId) &&
      presentString(wallet?.vaultPublicKey) &&
      (presentString(wallet?.agentKeyId) || presentString(config.agentKeyId)),
  );
}

export async function applySharedConfigToExistingWallet(
  originalConfig: WlfiConfig,
  updatedConfig: WlfiConfig,
  options: SharedConfigWalletApplyOptions,
  deps: SharedConfigWalletApplyDeps = {},
): Promise<SharedConfigWalletApplyResult> {
  if (!hasExistingWalletApplyTarget(updatedConfig)) {
    return { applied: false };
  }

  const platform = deps.platform ?? process.platform;
  if (!supportsManagedDaemonPlatform(platform)) {
    return { applied: false };
  }

  const resolveDaemonSocket =
    deps.resolveValidatedAdminDaemonSocket ?? resolveValidatedAdminDaemonSocket;
  const resolveVaultPassword =
    deps.resolveAdminSetupVaultPassword ?? resolveAdminSetupVaultPassword;
  const resolveBootstrapOutput =
    deps.resolveWalletSetupBootstrapOutputPath ?? resolveWalletSetupBootstrapOutputPath;
  const resolveCleanupAction =
    deps.resolveWalletSetupCleanupAction ?? resolveWalletSetupCleanupAction;
  const buildAdminArgs = deps.buildWalletSetupAdminArgs ?? buildWalletSetupAdminArgs;
  const runAdminBinary = deps.runRustBinary ?? runRustBinary;
  const finishWalletSetup = deps.completeWalletSetup ?? completeWalletSetup;
  const restoreConfig = deps.writeConfig ?? writeConfig;
  const deleteBootstrapFile =
    deps.deleteBootstrapAgentCredentialsFile ?? deleteBootstrapAgentCredentialsFile;

  const wallet = updatedConfig.wallet!;
  const bootstrapOutput = resolveBootstrapOutput();
  const cleanupAction = resolveCleanupAction(bootstrapOutput.autoGenerated, false);

  try {
    const daemonSocket = resolveDaemonSocket(options.daemonSocket, updatedConfig);
    const vaultPassword = await resolveVaultPassword({
      vaultPasswordStdin: options.vaultPasswordStdin,
      nonInteractive: options.nonInteractive,
    });

    await runAdminBinary(
      'agentpay-admin',
      buildAdminArgs({
        bootstrapOutputPath: bootstrapOutput.path,
        daemonSocket,
        fromSharedConfig: true,
        existingVaultKeyId: wallet.vaultKeyId,
        existingVaultPublicKey: wallet.vaultPublicKey,
        vaultPasswordStdin: true,
        nonInteractive: options.nonInteractive,
      }),
      updatedConfig,
      {
        stdin: `${vaultPassword}\n`,
        preSuppliedSecretStdin: 'vaultPassword',
      },
    );

    return {
      applied: true,
      daemonSocket,
      walletSetup: finishWalletSetup({
        bootstrapOutputPath: bootstrapOutput.path,
        cleanupAction,
        daemonSocket,
      }),
    };
  } catch (error) {
    restoreConfig(originalConfig);
    try {
      deleteBootstrapFile(bootstrapOutput.path);
    } catch {}
    throw error;
  }
}
