import { PublicKey } from '@solana/web3.js';
import type { Address, Hex } from 'viem';
import { isAddress } from 'viem';
import { publicKeyToAddress } from 'viem/accounts';
import {
  BUILTIN_CHAINS,
  BUILTIN_TOKENS,
  type ChainFamily,
  resolveChainProfile,
  type WalletKeyAlgorithm,
  type WalletProfile,
  type WlfiConfig,
} from '../../packages/config/src/index.js';
import { listAutoGeneratedBootstrapArtifacts } from './bootstrap-artifacts.js';
import {
  type BootstrapSetupSummary,
  readBootstrapSetupSummaryFile,
} from './bootstrap-credentials.js';
import { isMacOsPlatform } from './platform-support.js';

function presentString(value: string | undefined | null): string | undefined {
  const normalized = value?.trim();
  return normalized ? normalized : undefined;
}

function renderError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function normalizePublicKeyHex(value: string): Hex {
  const normalized = value.trim();
  return (normalized.startsWith('0x') ? normalized : `0x${normalized}`) as Hex;
}

function normalizeWalletKeyAlgorithm(
  value: WalletKeyAlgorithm | undefined | null,
): WalletKeyAlgorithm {
  return value === 'ed25519' ? 'ed25519' : 'secp256k1';
}

function deriveEvmWalletAddress(vaultPublicKey: string): string | undefined {
  try {
    return publicKeyToAddress(normalizePublicKeyHex(vaultPublicKey));
  } catch {
    return undefined;
  }
}

export function deriveSolanaWalletAddress(solanaPublicKey: string): string | undefined {
  try {
    const normalized = solanaPublicKey.trim().replace(/^0x/iu, '');
    if (!/^[0-9a-fA-F]{64}$/u.test(normalized)) {
      return undefined;
    }
    return new PublicKey(Buffer.from(normalized, 'hex')).toBase58();
  } catch {
    return undefined;
  }
}

export function deriveWalletAddress(
  vaultPublicKey: string,
  algorithm: WalletKeyAlgorithm | undefined = 'secp256k1',
): string | undefined {
  return normalizeWalletKeyAlgorithm(algorithm) === 'ed25519'
    ? deriveSolanaWalletAddress(vaultPublicKey)
    : deriveEvmWalletAddress(vaultPublicKey);
}

function renderWalletProfileRecoveryHint(platform: NodeJS.Platform = process.platform): string {
  if (isMacOsPlatform(platform)) {
    return 'rerun `agentpay admin setup` or import a bootstrap file first';
  }

  if (platform === 'linux') {
    return 'rerun `agentpay admin setup` or import a bootstrap file first';
  }

  return 'managed wallet setup is currently supported on macOS and Linux only';
}

function findMatchingBootstrapSummary(
  profile: WalletProfile | undefined,
): BootstrapSetupSummary | undefined {
  /* c8 ignore next 3 -- resolveWalletProfile only calls this helper when config.wallet is present */
  if (!profile) {
    return undefined;
  }

  const persistedAgentKeyId = presentString(profile.agentKeyId);
  const persistedPublicKey = presentString(profile.vaultPublicKey);
  const persistedSolanaPublicKey = presentString(profile.solanaPublicKey);
  const persistedSolanaAddress = presentString(profile.solanaAddress);
  const persistedAlgorithm = normalizeWalletKeyAlgorithm(profile.algorithm);
  const persistedAddress =
    presentString(profile.address) ??
    (persistedPublicKey ? deriveWalletAddress(persistedPublicKey, persistedAlgorithm) : undefined);

  return listAutoGeneratedBootstrapArtifacts()
    .filter(
      (artifact) =>
        (artifact.status === 'plaintext' || artifact.status === 'redacted') &&
        !artifact.leaseExpired,
    )
    .map((artifact) => readBootstrapSetupSummaryFile(artifact.path))
    .find((summary) => {
      if (persistedAgentKeyId && summary.agentKeyId === persistedAgentKeyId) {
        return true;
      }

      if (persistedPublicKey && summary.vaultPublicKey === persistedPublicKey) {
        return true;
      }

      if (persistedSolanaPublicKey && summary.solanaPublicKey === persistedSolanaPublicKey) {
        return true;
      }

      const summarySolanaAddress =
        presentString(summary.solanaAddress) ??
        (summary.solanaPublicKey ? deriveSolanaWalletAddress(summary.solanaPublicKey) : undefined);
      if (
        persistedSolanaAddress &&
        summarySolanaAddress &&
        persistedSolanaAddress === summarySolanaAddress
      ) {
        return true;
      }

      const summaryAddress = deriveWalletAddress(summary.vaultPublicKey, summary.vaultKeyAlgorithm);
      return Boolean(persistedAddress && summaryAddress && summaryAddress === persistedAddress);
    });
}

export function walletProfileFromBootstrapSummary(summary: BootstrapSetupSummary): WalletProfile {
  const algorithm = normalizeWalletKeyAlgorithm(summary.vaultKeyAlgorithm);
  const solanaPublicKey = presentString(summary.solanaPublicKey);
  const solanaAddress =
    presentString(summary.solanaAddress) ??
    (solanaPublicKey ? deriveSolanaWalletAddress(solanaPublicKey) : undefined);
  return {
    vaultKeyId: presentString(summary.vaultKeyId) ?? summary.vaultKeyId,
    algorithm,
    vaultPublicKey: presentString(summary.vaultPublicKey) ?? summary.vaultPublicKey,
    address: deriveWalletAddress(summary.vaultPublicKey, algorithm),
    solanaPublicKey,
    solanaAddress,
    agentKeyId: presentString(summary.agentKeyId),
    policyAttachment: presentString(summary.policyAttachment) ?? summary.policyAttachment,
    attachedPolicyIds:
      summary.attachedPolicyIds.length > 0 ? [...summary.attachedPolicyIds] : undefined,
    policyNote: presentString(summary.policyNote),
    networkScope: presentString(summary.networkScope),
    assetScope: presentString(summary.assetScope),
    recipientScope: presentString(summary.recipientScope),
  };
}

export function resolveWalletProfile(config: WlfiConfig): WalletProfile {
  if (config.wallet?.vaultPublicKey && config.wallet?.policyAttachment) {
    const matchingBootstrap = findMatchingBootstrapSummary(config.wallet);
    const algorithm = normalizeWalletKeyAlgorithm(
      config.wallet.algorithm ?? matchingBootstrap?.vaultKeyAlgorithm,
    );
    return {
      ...config.wallet,
      algorithm,
      vaultKeyId: config.wallet.vaultKeyId ?? matchingBootstrap?.vaultKeyId,
      address:
        config.wallet.address ?? deriveWalletAddress(config.wallet.vaultPublicKey, algorithm),
      solanaPublicKey:
        config.wallet.solanaPublicKey ?? matchingBootstrap?.solanaPublicKey ?? undefined,
      solanaAddress:
        config.wallet.solanaAddress ??
        matchingBootstrap?.solanaAddress ??
        (config.wallet.solanaPublicKey
          ? deriveSolanaWalletAddress(config.wallet.solanaPublicKey)
          : matchingBootstrap?.solanaPublicKey
            ? deriveSolanaWalletAddress(matchingBootstrap.solanaPublicKey)
            : undefined),
    };
  }

  const bootstrapArtifact = listAutoGeneratedBootstrapArtifacts().find(
    (artifact) =>
      (artifact.status === 'plaintext' || artifact.status === 'redacted') && !artifact.leaseExpired,
  );
  if (!bootstrapArtifact) {
    throw new Error(`wallet metadata is unavailable; ${renderWalletProfileRecoveryHint()}`);
  }

  return walletProfileFromBootstrapSummary(readBootstrapSetupSummaryFile(bootstrapArtifact.path));
}

export function resolveWalletAddress(config: WlfiConfig): Address {
  const profile = resolveWalletProfile(config);
  if (normalizeWalletKeyAlgorithm(profile.algorithm) !== 'secp256k1') {
    throw new Error(
      'wallet address is EVM-only; use the Solana wallet helpers for ed25519 wallets',
    );
  }
  /* c8 ignore next -- explicit-address and derived-address paths are both exercised, but c8 misattributes this nullish expression under --experimental-strip-types */
  const address =
    presentString(profile.address) ?? deriveWalletAddress(profile.vaultPublicKey, 'secp256k1');
  if (!address || !isAddress(address)) {
    throw new Error(`wallet address is unavailable; ${renderWalletProfileRecoveryHint()}`);
  }

  return address;
}

export interface WalletBalanceEntry {
  tokenKey: string;
  symbol: string;
  name?: string;
  chainKey: string;
  chainName: string;
  chainId: number;
  rpcUrl: string;
  kind: 'native' | 'erc20' | 'sol' | 'spl';
  tokenAddress: string;
  decimals: number;
  balance?: {
    raw: string;
    formatted: string;
  };
  error?: string;
}

export interface WalletProfileWithBalances extends WalletProfile {
  balances: WalletBalanceEntry[];
}

interface ResolveWalletProfileWithBalancesDeps {
  getNativeBalance: (
    rpcUrl: string,
    address: Address,
  ) => Promise<{
    raw: bigint;
    formatted: string;
  }>;
  getTokenBalance: (
    rpcUrl: string,
    token: Address,
    owner: Address,
    decimals?: number,
  ) => Promise<{
    raw: bigint;
    decimals: number;
    name: string | null;
    symbol: string | null;
    formatted: string;
  }>;
  getSplTokenBalance: (
    rpcUrl: string,
    mint: string,
    owner: string,
    decimals: number,
  ) => Promise<{
    raw: bigint;
    decimals: number;
    formatted: string;
  }>;
  getSolanaNativeBalance: (
    rpcUrl: string,
    owner: string,
  ) => Promise<{
    raw: bigint;
    formatted: string;
  }>;
}

interface WalletBalanceTarget {
  tokenKey: string;
  symbol: string;
  name?: string;
  chainKey: string;
  chainName: string;
  chainId: number;
  rpcUrl: string;
  isNative: boolean;
  tokenAddress: string;
  decimals: number;
  family: ChainFamily;
}

const TEMPO_CHAIN_IDS = new Set([4217, 42431]);

function toWalletBalanceTarget(
  tokenKey: string,
  tokenProfile: {
    symbol: string;
    name?: string;
  },
  chainKey: string,
  chainProfile: {
    chainId: number;
    isNative: boolean;
    address?: string;
    decimals: number;
  },
  resolvedChain: ReturnType<typeof resolveChainProfile>,
): WalletBalanceTarget | null {
  const rpcUrl = presentString(resolvedChain?.rpcUrl);
  if (!rpcUrl) {
    return null;
  }

  return {
    tokenKey,
    symbol: tokenProfile.symbol,
    name: tokenProfile.name,
    chainKey,
    /* c8 ignore next -- resolveChainProfile only yields usable balance targets when a chain name is available */
    chainName: resolvedChain?.name ?? chainKey,
    chainId: chainProfile.chainId,
    rpcUrl,
    isNative: chainProfile.isNative,
    tokenAddress: chainProfile.isNative ? 'native' : (presentString(chainProfile.address) ?? ''),
    decimals: chainProfile.decimals,
    family: resolvedChain?.family ?? 'evm',
  };
}

function findBuiltinNativeTokenForChain(
  chainKey: string,
  chainName: string | undefined,
): {
  tokenKey: string;
  tokenProfile: {
    symbol: string;
    name?: string;
  };
  chainProfile: {
    chainId: number;
    isNative: true;
    decimals: number;
  };
} | null {
  const selectors = new Set(
    [chainKey, chainName]
      .map((value) => value?.trim().toLowerCase())
      .filter((value): value is string => Boolean(value)),
  );

  for (const [tokenKey, tokenProfile] of Object.entries(BUILTIN_TOKENS)) {
    for (const builtinChainProfile of Object.values(tokenProfile.chains ?? {})) {
      if (!builtinChainProfile.isNative) {
        continue;
      }

      const matchesBuiltinAlias = Object.entries(BUILTIN_CHAINS).some(
        ([builtinChainKey, builtinChain]) =>
          builtinChain.chainId === builtinChainProfile.chainId &&
          selectors.has(builtinChainKey.toLowerCase()),
      );
      if (matchesBuiltinAlias) {
        return {
          tokenKey,
          tokenProfile: {
            symbol: tokenProfile.symbol,
            name: tokenProfile.name ?? tokenProfile.symbol,
          },
          chainProfile: {
            chainId: builtinChainProfile.chainId,
            isNative: true,
            decimals: builtinChainProfile.decimals,
          },
        };
      }
    }
  }

  return null;
}

function collectWalletBalanceTargets(config: WlfiConfig): WalletBalanceTarget[] {
  const configuredTargets = Object.entries(config.tokens ?? {})
    .flatMap(([tokenKey, tokenProfile]) =>
      Object.entries(tokenProfile.chains ?? {}).flatMap(([chainKey, chainProfile]) => {
        const target = toWalletBalanceTarget(
          tokenKey,
          tokenProfile,
          chainKey,
          chainProfile,
          resolveChainProfile(chainKey, config),
        );
        return target ? [target] : [];
      }),
    )
    .filter((target) => !(target.isNative && TEMPO_CHAIN_IDS.has(target.chainId)));

  const nativeChainIds = new Set(
    configuredTargets.filter((target) => target.isNative).map((target) => target.chainId),
  );

  const builtinNativeTargets = Object.entries(config.chains ?? {}).flatMap(
    ([chainKey, chainProfile]) => {
      if (TEMPO_CHAIN_IDS.has(chainProfile.chainId)) {
        return [];
      }
      if (nativeChainIds.has(chainProfile.chainId)) {
        return [];
      }

      const builtinNativeToken = findBuiltinNativeTokenForChain(chainKey, chainProfile.name);
      if (!builtinNativeToken) {
        return [];
      }

      const target = toWalletBalanceTarget(
        builtinNativeToken.tokenKey,
        builtinNativeToken.tokenProfile,
        chainKey,
        builtinNativeToken.chainProfile,
        resolveChainProfile(chainKey, config),
      );
      return target ? [target] : [];
    },
  );

  return [...configuredTargets, ...builtinNativeTargets].sort(
    (left, right) =>
      left.chainId - right.chainId ||
      left.chainKey.localeCompare(right.chainKey) ||
      left.symbol.localeCompare(right.symbol) ||
      left.tokenKey.localeCompare(right.tokenKey),
  );
}

export async function resolveWalletProfileWithBalances(
  config: WlfiConfig,
  deps: ResolveWalletProfileWithBalancesDeps,
): Promise<WalletProfileWithBalances> {
  const profile = resolveWalletProfile(config);
  const owner =
    normalizeWalletKeyAlgorithm(profile.algorithm) === 'secp256k1'
      ? resolveWalletAddress(config)
      : undefined;
  const solanaOwner =
    presentString(profile.solanaAddress) ??
    (normalizeWalletKeyAlgorithm(profile.algorithm) === 'ed25519'
      ? presentString(profile.address)
      : undefined);
  const nativeBalance = deps.getNativeBalance;
  const erc20Balance = deps.getTokenBalance;
  const splBalance = deps.getSplTokenBalance;
  const solBalance = deps.getSolanaNativeBalance;

  const balances = await Promise.all(
    collectWalletBalanceTargets(config).map(async (target): Promise<WalletBalanceEntry> => {
      if (target.family === 'solana' && target.isNative) {
        if (!solanaOwner) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'sol',
            tokenAddress: 'native',
            decimals: target.decimals,
            error:
              'wallet has no Solana address; rerun `agentpay admin setup` to enable Solana support',
          };
        }
        try {
          const balance = await solBalance(target.rpcUrl, solanaOwner);
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'sol',
            tokenAddress: 'native',
            decimals: target.decimals,
            balance: {
              raw: balance.raw.toString(),
              formatted: balance.formatted,
            },
          };
        } catch (error) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'sol',
            tokenAddress: 'native',
            decimals: target.decimals,
            error: renderError(error),
          };
        }
      }

      if (target.isNative) {
        if (!owner) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'native',
            tokenAddress: target.tokenAddress,
            decimals: target.decimals,
            error: 'wallet has no EVM address; use a secp256k1 wallet for EVM balances',
          };
        }
        try {
          const balance = await nativeBalance(target.rpcUrl, owner);
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'native',
            tokenAddress: target.tokenAddress,
            decimals: target.decimals,
            balance: {
              raw: balance.raw.toString(),
              formatted: balance.formatted,
            },
          };
        } catch (error) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'native',
            tokenAddress: target.tokenAddress,
            decimals: target.decimals,
            error: renderError(error),
          };
        }
      }

      if (target.family === 'solana') {
        if (!solanaOwner) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'spl',
            tokenAddress: target.tokenAddress || '<unset>',
            decimals: target.decimals,
            error:
              'wallet has no Solana address; rerun `agentpay admin setup` to enable Solana support',
          };
        }
        if (!target.tokenAddress) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'spl',
            tokenAddress: '<unset>',
            decimals: target.decimals,
            error: `configured token mint for ${target.tokenKey} on ${target.chainKey} is missing`,
          };
        }
        try {
          const balance = await splBalance(
            target.rpcUrl,
            target.tokenAddress,
            solanaOwner,
            target.decimals,
          );
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'spl',
            tokenAddress: target.tokenAddress,
            decimals: balance.decimals,
            balance: {
              raw: balance.raw.toString(),
              formatted: balance.formatted,
            },
          };
        } catch (error) {
          return {
            tokenKey: target.tokenKey,
            symbol: target.symbol,
            name: target.name,
            chainKey: target.chainKey,
            chainName: target.chainName,
            chainId: target.chainId,
            rpcUrl: target.rpcUrl,
            kind: 'spl',
            tokenAddress: target.tokenAddress,
            decimals: target.decimals,
            error: renderError(error),
          };
        }
      }

      if (!isAddress(target.tokenAddress)) {
        return {
          tokenKey: target.tokenKey,
          symbol: target.symbol,
          name: target.name,
          chainKey: target.chainKey,
          chainName: target.chainName,
          chainId: target.chainId,
          rpcUrl: target.rpcUrl,
          kind: 'erc20',
          tokenAddress: target.tokenAddress || '<unset>',
          decimals: target.decimals,
          error: `configured token address for ${target.tokenKey} on ${target.chainKey} is invalid`,
        };
      }

      try {
        if (!owner) {
          throw new Error('wallet has no EVM address; use a secp256k1 wallet for EVM balances');
        }
        const balance = await erc20Balance(
          target.rpcUrl,
          target.tokenAddress as Address,
          owner,
          target.decimals,
        );
        return {
          tokenKey: target.tokenKey,
          symbol: balance.symbol ?? target.symbol,
          name: balance.name ?? target.name,
          chainKey: target.chainKey,
          chainName: target.chainName,
          chainId: target.chainId,
          rpcUrl: target.rpcUrl,
          kind: 'erc20',
          tokenAddress: target.tokenAddress,
          decimals: balance.decimals,
          balance: {
            raw: balance.raw.toString(),
            formatted: balance.formatted,
          },
        };
      } catch (error) {
        return {
          tokenKey: target.tokenKey,
          symbol: target.symbol,
          name: target.name,
          chainKey: target.chainKey,
          chainName: target.chainName,
          chainId: target.chainId,
          rpcUrl: target.rpcUrl,
          kind: 'erc20',
          tokenAddress: target.tokenAddress,
          decimals: target.decimals,
          error: renderError(error),
        };
      }
    }),
  );

  return {
    ...profile,
    balances,
  };
}

export function formatWalletProfileText(
  profile: WalletProfile | WalletProfileWithBalances,
): string {
  const lines = [
    `Algorithm: ${normalizeWalletKeyAlgorithm(profile.algorithm)}`,
    `Public Key: ${profile.vaultPublicKey}`,
    profile.address ? `Address: ${profile.address}` : null,
    profile.solanaAddress ? `Solana Address: ${profile.solanaAddress}` : null,
    profile.solanaPublicKey ? `Solana Public Key: ${profile.solanaPublicKey}` : null,
    profile.agentKeyId ? `Agent Key ID: ${profile.agentKeyId}` : null,
    `Policy Attachment: ${profile.policyAttachment}`,
    profile.policyNote ? `Policy Note: ${profile.policyNote}` : null,
    profile.networkScope ? `Network Scope: ${profile.networkScope}` : null,
    profile.assetScope ? `Asset Scope: ${profile.assetScope}` : null,
    profile.recipientScope ? `Recipient Scope: ${profile.recipientScope}` : null,
    profile.attachedPolicyIds?.length
      ? `Attached Policy IDs: ${profile.attachedPolicyIds.join(', ')}`
      : null,
  ];

  if ('balances' in profile && Array.isArray(profile.balances) && profile.balances.length > 0) {
    lines.push('Balances:');
    lines.push(
      ...profile.balances.map((balance) => {
        const label = `${balance.symbol} on ${balance.chainKey} (${balance.chainId})`;
        if (balance.error) {
          return `- ${label}: error: ${balance.error}`;
        }
        return `- ${label}: ${balance.balance?.formatted ?? '0'}`;
      }),
    );
  }

  return lines.filter((line): line is string => Boolean(line)).join('\n');
}
