import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

const modulePath = new URL('../src/lib/bootstrap-artifacts.ts', import.meta.url);

function loadModule(caseId) {
  return import(modulePath.href + `?case=${caseId}`);
}

function writePrivateJsonFile(targetPath, payload) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true, mode: 0o700 });
  fs.writeFileSync(targetPath, JSON.stringify(payload, null, 2) + '\n', {
    encoding: 'utf8',
    mode: 0o600,
  });
  fs.chmodSync(targetPath, 0o600);
}

function bootstrapPayload(overrides = {}) {
  const payload = {
    state_file: 'daemon_socket:/tmp/agentpay.sock',
    lease_id: 'lease-123',
    lease_expires_at: '2099-01-01T00:00:00Z',
    per_tx_policy_id: 'policy-per-tx',
    daily_policy_id: 'policy-daily',
    weekly_policy_id: 'policy-weekly',
    gas_policy_id: 'policy-gas',
    per_tx_max_wei: '1000000000000000000',
    daily_max_wei: '5000000000000000000',
    weekly_max_wei: '20000000000000000000',
    max_gas_per_chain_wei: '1000000000000000',
    vault_key_id: 'vault-key-123',
    vault_public_key: '03abcdef',
    agent_key_id: '00000000-0000-0000-0000-000000000001',
    agent_auth_token: 'secret-agent-token',
    agent_auth_token_redacted: false,
    network_scope: 'all networks',
    asset_scope: 'all assets',
    recipient_scope: 'all recipients',
    policy_attachment: 'policy_set',
    attached_policy_ids: undefined,
    policy_note: 'bootstrap note',
    ...overrides,
  };

  if (!('attached_policy_ids' in overrides)) {
    payload.attached_policy_ids = [
      payload.per_tx_policy_id,
      payload.daily_policy_id,
      payload.weekly_policy_id,
      payload.gas_policy_id,
    ].filter((value) => typeof value === 'string');
  }

  return payload;
}

test('listAutoGeneratedBootstrapArtifacts reports plaintext and redacted files', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-list-states`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  writePrivateJsonFile(path.join(tempRoot, 'bootstrap-100-200.json'), bootstrapPayload());
  writePrivateJsonFile(
    path.join(tempRoot, 'bootstrap-300-400.json'),
    bootstrapPayload({
      agent_auth_token: '<redacted>',
      agent_auth_token_redacted: true,
    }),
  );
  writePrivateJsonFile(path.join(tempRoot, 'notes.json'), { hello: 'world' });

  const result = bootstrapArtifacts.listAutoGeneratedBootstrapArtifacts({
    resolveAgentPayHome: () => tempRoot,
  });

  assert.equal(result.length, 2);
  assert.deepEqual(
    result.map((entry) => [path.basename(entry.path), entry.status]),
    [
      ['bootstrap-300-400.json', 'redacted'],
      ['bootstrap-100-200.json', 'plaintext'],
    ],
  );
  assert.equal(result[0].error, null);
  assert.equal(result[1].error, null);
  assert.equal(result[0].leaseExpired, false);
  assert.equal(result[1].leaseExpired, false);
});

test('inspectBootstrapArtifact reports invalid and untrusted bootstrap files', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-invalid-untrusted`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const invalidPath = path.join(tempRoot, 'bootstrap-500-600.json');
  writePrivateJsonFile(invalidPath, { hello: 'world' });

  const invalidResult = bootstrapArtifacts.inspectBootstrapArtifact(invalidPath);
  assert.equal(invalidResult.status, 'invalid');
  assert.match(
    invalidResult.error ?? '',
    /lease_id is required|must contain a JSON object|policy_attachment is required|missing token_policies and legacy policy ids/,
  );

  if (process.platform !== 'win32') {
    const symlinkTarget = path.join(tempRoot, 'real-bootstrap.json');
    writePrivateJsonFile(symlinkTarget, bootstrapPayload());
    const symlinkPath = path.join(tempRoot, 'bootstrap-700-800.json');
    fs.symlinkSync(symlinkTarget, symlinkPath);

    const untrustedResult = bootstrapArtifacts.inspectBootstrapArtifact(symlinkPath);
    assert.equal(untrustedResult.status, 'untrusted');
    assert.match(untrustedResult.error ?? '', /must not be a symlink/);
  }
});

test('inspectBootstrapArtifact keeps files plaintext when a vault private key remains after token redaction', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-redacted-token-plaintext-key`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const bootstrapPath = path.join(tempRoot, 'bootstrap-900-1000.json');
  writePrivateJsonFile(
    bootstrapPath,
    bootstrapPayload({
      agent_auth_token: '<redacted>',
      agent_auth_token_redacted: true,
      vault_private_key: '11'.repeat(32),
    }),
  );

  const result = bootstrapArtifacts.inspectBootstrapArtifact(bootstrapPath);
  assert.equal(result.status, 'plaintext');
  assert.equal(result.agentKeyId, '00000000-0000-0000-0000-000000000001');
  assert.equal(result.leaseExpiresAt, '2099-01-01T00:00:00Z');
  assert.equal(result.leaseExpired, false);
  assert.equal(result.error, null);
});

test('inspectBootstrapArtifact marks expired bootstrap leases without treating them as malformed', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-expired-lease`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const bootstrapPath = path.join(tempRoot, 'bootstrap-1100-1200.json');
  writePrivateJsonFile(
    bootstrapPath,
    bootstrapPayload({
      lease_expires_at: '2000-01-01T00:00:00Z',
    }),
  );

  const result = bootstrapArtifacts.inspectBootstrapArtifact(bootstrapPath);
  assert.equal(result.status, 'plaintext');
  assert.equal(result.leaseExpired, true);
  assert.equal(result.error, null);
});

test('cleanupAutoGeneratedBootstrapArtifacts deletes recognized bootstrap files by default', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-cleanup-delete`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const plaintextPath = path.join(tempRoot, 'bootstrap-100-200.json');
  const redactedPath = path.join(tempRoot, 'bootstrap-300-400.json');
  const invalidPath = path.join(tempRoot, 'bootstrap-500-600.json');

  writePrivateJsonFile(plaintextPath, bootstrapPayload());
  writePrivateJsonFile(
    redactedPath,
    bootstrapPayload({
      agent_auth_token: '<redacted>',
      agent_auth_token_redacted: true,
    }),
  );
  writePrivateJsonFile(invalidPath, { hello: 'world' });

  const result = bootstrapArtifacts.cleanupAutoGeneratedBootstrapArtifacts('deleted', {
    resolveAgentPayHome: () => tempRoot,
  });

  assert.equal(result.action, 'deleted');
  assert.deepEqual(
    result.files.map((entry) => [path.basename(entry.path), entry.cleanup]),
    [
      ['bootstrap-500-600.json', 'skipped'],
      ['bootstrap-300-400.json', 'deleted'],
      ['bootstrap-100-200.json', 'deleted'],
    ],
  );
  assert.equal(fs.existsSync(plaintextPath), false);
  assert.equal(fs.existsSync(redactedPath), false);
  assert.equal(fs.existsSync(invalidPath), true);
});

test('cleanupAutoGeneratedBootstrapArtifacts can redact plaintext files in place', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-cleanup-redact`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const plaintextPath = path.join(tempRoot, 'bootstrap-100-200.json');
  writePrivateJsonFile(plaintextPath, bootstrapPayload());

  const result = bootstrapArtifacts.cleanupAutoGeneratedBootstrapArtifacts('redacted', {
    resolveAgentPayHome: () => tempRoot,
  });

  assert.equal(result.action, 'redacted');
  assert.equal(result.files.length, 1);
  assert.equal(result.files[0].cleanup, 'redacted');
  assert.equal(fs.existsSync(plaintextPath), true);

  const inspected = bootstrapArtifacts.inspectBootstrapArtifact(plaintextPath);
  assert.equal(inspected.status, 'redacted');
});

test('cleanupAutoGeneratedBootstrapArtifacts redacts files that still contain a plaintext vault private key', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-cleanup-plaintext-private-key`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const plaintextPath = path.join(tempRoot, 'bootstrap-100-200.json');
  writePrivateJsonFile(
    plaintextPath,
    bootstrapPayload({
      agent_auth_token: '<redacted>',
      agent_auth_token_redacted: true,
      vault_private_key: '11'.repeat(32),
    }),
  );

  const result = bootstrapArtifacts.cleanupAutoGeneratedBootstrapArtifacts('redacted', {
    resolveAgentPayHome: () => tempRoot,
  });

  assert.equal(result.action, 'redacted');
  assert.equal(result.files.length, 1);
  assert.equal(result.files[0].cleanup, 'redacted');
  assert.equal(fs.existsSync(plaintextPath), true);

  const inspected = bootstrapArtifacts.inspectBootstrapArtifact(plaintextPath);
  assert.equal(inspected.status, 'redacted');
});

test('cleanupAutoGeneratedBootstrapArtifacts reports failed redaction cleanup when fallback delete also fails', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-cleanup-redact-failure`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const plaintextPath = path.join(tempRoot, 'bootstrap-100-200.json');
  writePrivateJsonFile(plaintextPath, bootstrapPayload());

  const originalRenameSync = fs.renameSync;
  const originalRmSync = fs.rmSync;
  fs.renameSync = () => {
    throw new Error('rename failed');
  };
  fs.rmSync = (targetPath, ...args) => {
    if (path.resolve(String(targetPath)) === plaintextPath) {
      throw new Error('delete failed');
    }
    return originalRmSync.call(fs, targetPath, ...args);
  };

  try {
    const result = bootstrapArtifacts.cleanupAutoGeneratedBootstrapArtifacts('redacted', {
      resolveAgentPayHome: () => tempRoot,
    });

    assert.equal(result.action, 'redacted');
    assert.equal(result.files.length, 1);
    assert.equal(result.files[0].cleanup, 'failed');
    assert.match(result.files[0].error ?? '', /rename failed/);
    assert.match(result.files[0].error ?? '', /fallback delete also failed: delete failed/);
  } finally {
    fs.renameSync = originalRenameSync;
    fs.rmSync = originalRmSync;
  }

  assert.equal(fs.existsSync(plaintextPath), true);
});

test('listAutoGeneratedBootstrapArtifacts fails closed for untrusted homes and tolerates missing directories', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-list-home-edge-cases`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  if (process.platform !== 'win32') {
    const realHome = path.join(tempRoot, 'real-home');
    fs.mkdirSync(realHome, { recursive: true, mode: 0o700 });
    fs.chmodSync(realHome, 0o700);
    const symlinkHome = path.join(tempRoot, 'home-symlink');
    fs.symlinkSync(realHome, symlinkHome);
    assert.deepEqual(
      bootstrapArtifacts.listAutoGeneratedBootstrapArtifacts({
        resolveAgentPayHome: () => symlinkHome,
      }),
      [],
    );
  }

  const missing = bootstrapArtifacts.listAutoGeneratedBootstrapArtifacts({
    resolveAgentPayHome: () => tempRoot,
    readdirSync: () => {
      const error = new Error('missing home');
      error.code = 'ENOENT';
      throw error;
    },
  });
  assert.deepEqual(missing, []);

  assert.throws(
    () =>
      bootstrapArtifacts.listAutoGeneratedBootstrapArtifacts({
        resolveAgentPayHome: () => tempRoot,
        readdirSync: () => {
          throw new Error('readdir boom');
        },
      }),
    /readdir boom/,
  );
});

test('inspectBootstrapArtifact marks invalid lease metadata and malformed credential fields', async () => {
  const bootstrapArtifacts = await loadModule(
    `${Date.now()}-inspect-invalid-lease-and-credentials`,
  );
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  fs.chmodSync(tempRoot, 0o700);

  const invalidLeasePath = path.join(tempRoot, 'bootstrap-1300-1400.json');
  writePrivateJsonFile(
    invalidLeasePath,
    bootstrapPayload({
      lease_expires_at: 'not-an-iso-timestamp',
    }),
  );
  const leaseResult = bootstrapArtifacts.inspectBootstrapArtifact(invalidLeasePath);
  assert.equal(leaseResult.status, 'invalid');
  assert.equal(leaseResult.agentKeyId, '00000000-0000-0000-0000-000000000001');
  assert.equal(leaseResult.leaseExpiresAt, 'not-an-iso-timestamp');
  assert.match(leaseResult.error ?? '', /valid ISO-8601 timestamp/);

  const invalidCredentialPath = path.join(tempRoot, 'bootstrap-1500-1600.json');
  writePrivateJsonFile(
    invalidCredentialPath,
    bootstrapPayload({
      agent_auth_token: '',
    }),
  );
  const credentialsResult = bootstrapArtifacts.inspectBootstrapArtifact(invalidCredentialPath);
  assert.equal(credentialsResult.status, 'invalid');
  assert.equal(credentialsResult.agentKeyId, '00000000-0000-0000-0000-000000000001');
  assert.match(credentialsResult.error ?? '', /agent_auth_token is required/);
});

test('bootstrap artifact helpers use the default AGENTPAY_HOME when deps are omitted', async () => {
  const bootstrapArtifacts = await loadModule(`${Date.now()}-default-agentpay-home`);
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentpay-bootstrap-artifacts-'));
  const originalAgentPayHome = process.env.AGENTPAY_HOME;
  fs.chmodSync(tempRoot, 0o700);

  try {
    process.env.AGENTPAY_HOME = tempRoot;
    const bootstrapPath = path.join(tempRoot, 'bootstrap-1700-1800.json');
    writePrivateJsonFile(bootstrapPath, bootstrapPayload());

    const listed = bootstrapArtifacts.listAutoGeneratedBootstrapArtifacts();
    assert.equal(listed.length, 1);
    assert.equal(listed[0].status, 'plaintext');

    const cleaned = bootstrapArtifacts.cleanupAutoGeneratedBootstrapArtifacts('deleted');
    assert.equal(cleaned.files.length, 1);
    assert.equal(cleaned.files[0].cleanup, 'deleted');
    assert.equal(fs.existsSync(bootstrapPath), false);
  } finally {
    if (originalAgentPayHome === undefined) {
      delete process.env.AGENTPAY_HOME;
    } else {
      process.env.AGENTPAY_HOME = originalAgentPayHome;
    }
    fs.rmSync(tempRoot, { recursive: true, force: true });
  }
});
