import assert from 'node:assert/strict';
import test from 'node:test';

const modulePath = new URL('../src/lib/shared-config-apply.ts', import.meta.url);

const AGENT_KEY_ID = '00000000-0000-0000-0000-000000000123';
const VAULT_KEY_ID = '00000000-0000-0000-0000-000000000456';

function sampleUpdatedConfig() {
  return {
    agentKeyId: AGENT_KEY_ID,
    wallet: {
      vaultKeyId: VAULT_KEY_ID,
      vaultPublicKey: '03abcdef',
      agentKeyId: AGENT_KEY_ID,
      policyAttachment: 'policy_set',
      attachedPolicyIds: ['policy-old-1', 'policy-old-2'],
    },
  };
}

test('applySharedConfigToExistingWallet is a no-op when wallet reuse metadata is missing', async () => {
  const mod = await import(`${modulePath.href}?case=${Date.now()}-no-target`);
  let called = false;

  const result = await mod.applySharedConfigToExistingWallet(
    {},
    { wallet: { vaultPublicKey: '03abcdef', policyAttachment: 'policy_set' } },
    {},
    {
      runRustBinary: async () => {
        called = true;
        return { stdout: '', stderr: '', code: 0 };
      },
    },
  );

  assert.deepEqual(result, { applied: false });
  assert.equal(called, false);
});

test('applySharedConfigToExistingWallet supports Linux managed wallets when reuse metadata exists', async () => {
  const mod = await import(`${modulePath.href}?case=${Date.now()}-linux-supported`);
  let called = false;

  const result = await mod.applySharedConfigToExistingWallet(
    { tokens: {} },
    sampleUpdatedConfig(),
    {},
    {
      platform: 'linux',
      resolveValidatedAdminDaemonSocket: () => '/trusted/linux-daemon.sock',
      resolveAdminSetupVaultPassword: async () => 'vault-secret',
      resolveWalletSetupBootstrapOutputPath: () => ({
        path: '/tmp/linux-bootstrap-sync.json',
        autoGenerated: true,
      }),
      resolveWalletSetupCleanupAction: () => 'deleted',
      buildWalletSetupAdminArgs: () => ['--json', '--quiet', 'bootstrap'],
      runRustBinary: async () => {
        called = true;
        return { stdout: '', stderr: '', code: 0 };
      },
      completeWalletSetup: () => ({
        agentKeyId: AGENT_KEY_ID,
        policyAttachment: 'policy_set',
        attachedPolicyIds: ['policy-linux-1'],
      }),
    },
  );

  assert.equal(called, true);
  assert.deepEqual(result, {
    applied: true,
    daemonSocket: '/trusted/linux-daemon.sock',
    walletSetup: {
      agentKeyId: AGENT_KEY_ID,
      policyAttachment: 'policy_set',
      attachedPolicyIds: ['policy-linux-1'],
    },
  });
});

test('applySharedConfigToExistingWallet runs shared-config bootstrap and returns the refreshed wallet summary', async () => {
  const mod = await import(`${modulePath.href}?case=${Date.now()}-success`);
  const originalConfig = { tokens: { usd1: { symbol: 'USD1', chains: {} } } };
  const updatedConfig = sampleUpdatedConfig();
  let builtArgs = null;
  let spawned = null;

  const result = await mod.applySharedConfigToExistingWallet(
    originalConfig,
    updatedConfig,
    {
      daemonSocket: '/Library/AgentPay/run/daemon.sock',
      vaultPasswordStdin: true,
      nonInteractive: true,
    },
    {
      resolveValidatedAdminDaemonSocket: (explicitValue, config) => {
        assert.equal(explicitValue, '/Library/AgentPay/run/daemon.sock');
        assert.equal(config, updatedConfig);
        return '/trusted/daemon.sock';
      },
      resolveWalletSetupBootstrapOutputPath: () => ({
        path: '/tmp/bootstrap-sync.json',
        autoGenerated: true,
      }),
      resolveWalletSetupCleanupAction: (autoGeneratedOutput, deleteBootstrapOutput) => {
        assert.equal(autoGeneratedOutput, true);
        assert.equal(deleteBootstrapOutput, false);
        return 'deleted';
      },
      resolveAdminSetupVaultPassword: async (options) => {
        assert.deepEqual(options, {
          vaultPasswordStdin: true,
          nonInteractive: true,
        });
        return 'vault-secret';
      },
      buildWalletSetupAdminArgs: (input) => {
        builtArgs = input;
        return ['--json', '--quiet', 'bootstrap'];
      },
      runRustBinary: async (binaryName, args, config, options) => {
        spawned = { binaryName, args, config, options };
        return { stdout: '', stderr: '', code: 0 };
      },
      completeWalletSetup: (options) => {
        assert.deepEqual(options, {
          bootstrapOutputPath: '/tmp/bootstrap-sync.json',
          cleanupAction: 'deleted',
          daemonSocket: '/trusted/daemon.sock',
        });
        return {
          agentKeyId: AGENT_KEY_ID,
          policyAttachment: 'policy_set',
          attachedPolicyIds: ['policy-new-1', 'policy-new-2'],
        };
      },
    },
  );

  assert.deepEqual(builtArgs, {
    bootstrapOutputPath: '/tmp/bootstrap-sync.json',
    daemonSocket: '/trusted/daemon.sock',
    fromSharedConfig: true,
    existingVaultKeyId: VAULT_KEY_ID,
    existingVaultPublicKey: '03abcdef',
    vaultPasswordStdin: true,
    nonInteractive: true,
  });
  assert.deepEqual(spawned, {
    binaryName: 'agentpay-admin',
    args: ['--json', '--quiet', 'bootstrap'],
    config: updatedConfig,
    options: {
      stdin: 'vault-secret\n',
      preSuppliedSecretStdin: 'vaultPassword',
    },
  });
  assert.deepEqual(result, {
    applied: true,
    daemonSocket: '/trusted/daemon.sock',
    walletSetup: {
      agentKeyId: AGENT_KEY_ID,
      policyAttachment: 'policy_set',
      attachedPolicyIds: ['policy-new-1', 'policy-new-2'],
    },
  });
});

test('applySharedConfigToExistingWallet restores the original config when daemon apply fails', async () => {
  const mod = await import(`${modulePath.href}?case=${Date.now()}-rollback`);
  const originalConfig = { tokens: { usd1: { symbol: 'USD1', chains: {} } } };
  const updatedConfig = sampleUpdatedConfig();
  let restoredConfig = null;
  let deletedBootstrapPath = null;

  await assert.rejects(
    () =>
      mod.applySharedConfigToExistingWallet(
        originalConfig,
        updatedConfig,
        {
          daemonSocket: '/Library/AgentPay/run/daemon.sock',
          vaultPasswordStdin: true,
          nonInteractive: true,
        },
        {
          resolveValidatedAdminDaemonSocket: () => '/trusted/daemon.sock',
          resolveWalletSetupBootstrapOutputPath: () => ({
            path: '/tmp/bootstrap-sync.json',
            autoGenerated: true,
          }),
          resolveWalletSetupCleanupAction: () => 'deleted',
          resolveAdminSetupVaultPassword: async () => 'vault-secret',
          buildWalletSetupAdminArgs: () => ['--json', '--quiet', 'bootstrap'],
          runRustBinary: async () => {
            throw new Error('daemon apply failed');
          },
          writeConfig: (config) => {
            restoredConfig = config;
            return config;
          },
          deleteBootstrapAgentCredentialsFile: (inputPath) => {
            deletedBootstrapPath = inputPath;
            return { sourcePath: inputPath };
          },
        },
      ),
    /daemon apply failed/u,
  );

  assert.equal(restoredConfig, originalConfig);
  assert.equal(deletedBootstrapPath, '/tmp/bootstrap-sync.json');
});
