use std::fmt;

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;
use zeroize::{Zeroize, Zeroizing};

use crate::PolicyAttachment;

/// Source of private key material.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeySource {
    /// Key generated by backend.
    Generated,
    /// Key imported by backend.
    Imported,
}

/// Signing algorithm bound to a vault key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KeyAlgorithm {
    Secp256k1,
    Ed25519,
}

fn default_key_algorithm() -> KeyAlgorithm {
    KeyAlgorithm::Secp256k1
}

/// Public metadata for a vault signing key.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VaultKey {
    /// Stable key identifier.
    pub id: Uuid,
    /// How key was created.
    pub source: KeySource,
    /// Signing algorithm used by the key.
    #[serde(default = "default_key_algorithm")]
    pub algorithm: KeyAlgorithm,
    /// Uncompressed SEC1 public key bytes encoded as lowercase hex.
    pub public_key_hex: String,
    /// Creation timestamp.
    pub created_at: OffsetDateTime,
}

/// Agent key metadata.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentKey {
    /// Stable agent key identifier.
    pub id: Uuid,
    /// Linked vault key identifier.
    pub vault_key_id: Uuid,
    /// Policy attachment.
    pub policies: PolicyAttachment,
    /// Creation timestamp.
    pub created_at: OffsetDateTime,
}

/// Agent authentication material returned at provisioning time.
///
/// The `auth_token` is a bearer credential and must be treated like a secret:
/// it should be stored securely and never logged.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentCredentials {
    /// Public metadata for the provisioned agent key.
    pub agent_key: AgentKey,
    /// Secret bearer token required for signing requests.
    #[serde(with = "crate::serde_helpers::zeroizing_string")]
    pub auth_token: Zeroizing<String>,
}

impl fmt::Debug for AgentCredentials {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("AgentCredentials")
            .field("agent_key", &self.agent_key)
            .field("auth_token", &"<redacted>")
            .finish()
    }
}

impl AgentCredentials {
    pub fn zeroize_secrets(&mut self) {
        self.auth_token.zeroize();
    }
}
